// ============================================================
//  TechFairy Lab — Terminal Simulator
//  Fake Ubuntu filesystem + command execution engine
// ============================================================

type FSNode = { [key: string]: FSNode | string | null } | string | null;

type CommandResult = 
  | { type: "output" | "error" | "info"; text: string }
  | { type: "clear" }
  | { type: "exit"; text: string }
  | { type: "nano"; filename: string; absPath: string; content: string }
  | { type: "download"; filename: string; content: string }
  | { type: "export" }
  | null;

// ─────────────────────────────────────────────
//  FILESYSTEM
//  null  = directory
//  string = file content
// ─────────────────────────────────────────────
const FILESYSTEM: FSNode = {
  "": null, // root /
  bin: null,
  boot: null,
  cdrom: null,
  dev: null,
  etc: {
    "hosts": `127.0.0.1   localhost
127.0.1.1   labfae
::1         localhost ip6-localhost ip6-loopback
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters`,

    "passwd": `root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
user:x:1000:1000:User,,,:/home/user:/bin/bash`,

    "hostname": `labfae`,

    "os-release": `PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"`,

    "fstab": `# /etc/fstab: static file system information.
# <file system>  <mount point>  <type>  <options>  <dump>  <pass>
UUID=a1b2c3d4    /              ext4    errors=remount-ro 0  1
UUID=e5f6g7h8    /boot          ext4    defaults           0  2
UUID=i9j0k1l2    none           swap    sw                 0  0`,

    "resolv.conf": `# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
search labfae.local`,

    "bash.bashrc": `# System-wide .bashrc file for interactive bash shells.
if [ -z "$PS1" ]; then
  return
fi

HISTCONTROL=ignoredups:ignorespace
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'`,

    "crontab": `# /etc/crontab: system-wide crontab
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m  h  dom mon dow user  command
17 *   * * *   root  cd / && run-parts --report /etc/cron.hourly
25 6   * * *   root  test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6   * * 7   root  test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )`,
  },

  home: {
    user: {
      Desktop: {
        "welcome.txt": `Welcome to TechFairy Lab Terminal! 🧚
=========================================
This is a simulated Ubuntu terminal for
practicing Linux commands safely.

Start by exploring the filesystem:
  pwd       - where am I?
  ls        - what's here?
  cd ..     - go up a level
  cat /etc/os-release  - what system is this?

Good luck earning your Black Belt! 🥋
Created by labfae.com`,
      },

      Documents: {
        "notes.txt": `Linux is an open source operating system.
The terminal is a powerful tool for developers.
bash is the most common shell on Linux systems.
grep searches for patterns inside files.
echo prints text to the standard output.
sort arranges lines in alphabetical order.
pipes connect the output of one command to another.
permissions control who can read write or execute files.
the root user has full access to the entire system.
always be careful when running commands as root.`,

        "report.txt": `TechFairy Lab — Linux Learning Report
======================================
Date: 2024-01-15
Student: user
Progress: Chapter 3 — Navigating the Filesystem

Summary
-------
The student has completed chapters 1 and 2 covering
terminal basics and getting help. Key commands mastered:
echo, clear, history, man, whatis, which, whereis.

Current chapter covers pwd, ls, cd and tree.
The filesystem hierarchy is now familiar.

Next steps
----------
- Complete Chapter 4: Working with Files
- Practice touch, mkdir, cp, mv, rm
- Start reading about permissions in Chapter 13

Notes
-----
Remember: tab completion saves a lot of typing.
Use Ctrl+R to search command history.
The man pages are your best friend.`,

        "todo.txt": `[ ] Finish Chapter 3 - Navigating the Filesystem
[x] Complete Chapter 1 - What Is the Terminal
[x] Complete Chapter 2 - Getting Help
[ ] Practice grep on notes.txt
[ ] Learn about pipes and redirection
[ ] Set up my custom PS1 prompt
[ ] Install tmux and learn the basics
[ ] Practice vim motions daily
[ ] Read the bash man page
[ ] Complete all 34 chapters and earn Black Belt`,
      },

      Downloads: {
        "README.md": `# Downloads Folder
Files downloaded from the internet land here.

## Recent Downloads
- linux_cheatsheet.pdf (not yet saved)
- ubuntu-22.04-desktop.iso (not yet saved)

## Tip
Use wget or curl to download files from the terminal:
  wget https://example.com/file.txt
  curl -O https://example.com/file.txt`,
      },

      Music: {},
      Pictures: {},
      Public: {},
      Templates: {},
      Videos: {},

      Projects: {
        "hello.sh": `#!/bin/bash
# My first shell script
echo "Hello, World!"
echo "Welcome to bash scripting"`,

        "count.sh": `#!/bin/bash
# Count from 1 to 5
for i in 1 2 3 4 5; do
  echo "Count: $i"
done
echo "Done!"`,

        "backup.sh": `#!/bin/bash
# Simple backup script
SOURCE="/home/user/Documents"
DEST="/home/user/Downloads/backup"
DATE=$(date +%Y-%m-%d)

echo "Starting backup for $DATE..."
mkdir -p "$DEST"
cp -r "$SOURCE" "$DEST/documents_$DATE"
echo "Backup complete!"`,

        ".git": {
          HEAD: `ref: refs/heads/main`,
          "config": `[core]
  repositoryformatversion = 0
  filemode = true
  bare = false
[remote "origin"]
  url = git@github.com:user/projects.git
  fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
  remote = origin
  merge = refs/heads/main`,
        },
      },

      snap: {},

      ".bashrc": `# ~/.bashrc: executed by bash for non-login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# History settings
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s histappend

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias gs='git status'
alias glog='git log --oneline --graph'

# Prompt
PS1='[\\x1b[01;32m]\\u@\\h[\\x1b[00m]:[\\x1b[01;34m]\\w[\\x1b[00m]\\$ '

# Add local bin to PATH
export PATH="$HOME/.local/bin:$PATH"`,

      ".bash_profile": `# ~/.bash_profile: executed for login shells.

# Load .bashrc if it exists
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment
export EDITOR=nano
export VISUAL=nano
export LANG=en_US.UTF-8`,

      ".bash_history": `ls
pwd
cd Documents
cat notes.txt
grep "bash" notes.txt
cd ..
mkdir Projects
cd Projects
nano hello.sh
chmod +x hello.sh
./hello.sh
git init
git add .
git commit -m "first commit"
history`,

      ".ssh": {
        "config": `# SSH Client Configuration
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_ed25519

Host myserver
  HostName 192.168.1.100
  User user
  Port 22`,
        "known_hosts": `github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl`,
      },
    },
  },

  lib: null,
  lib64: null,
  "lost+found": null,
  media: null,
  mnt: null,
  opt: null,

  proc: {
    "cpuinfo": `processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
stepping	: 10
microcode	: 0xf0
cpu MHz		: 1800.000
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
bogomips	: 3600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual`,

    "meminfo": `MemTotal:        8048576 kB
MemFree:         2341256 kB
MemAvailable:    4521984 kB
Buffers:          312448 kB
Cached:          2048512 kB
SwapCached:            0 kB
Active:          3145728 kB
Inactive:        1572864 kB
SwapTotal:       2097152 kB
SwapFree:        2097152 kB
Dirty:              1024 kB
Writeback:             0 kB`,

    "version": `Linux version 5.15.0-91-generic (buildd@lcy02-amd64-007) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023`,

    "uptime": `1234567.89 987654.32`,
  },

  root: {
    ".bashrc": `# root's .bashrc
export PS1='[\\x1b[01;31m]\\u@\\h[\\x1b[00m]:[\\x1b[01;34m]\\w[\\x1b[00m]\\# '
alias ll='ls -alF'
alias la='ls -A'`,

    ".bash_history": `apt update
apt upgrade -y
useradd -m newuser
passwd newuser
systemctl restart nginx
journalctl -f
cat /etc/shadow
chmod 600 /etc/ssh/sshd_config
ufw enable
ufw allow 22`,

    "readme.txt": `This is the root home directory.
The root user has full system access.

With great power comes great responsibility.
Always double-check commands before running as root.
Use sudo instead of logging in as root when possible.

Common root tasks:
  - Managing users and groups
  - Installing system packages
  - Configuring services
  - Managing firewall rules`,
  },

  run: null,
  sbin: null,
  srv: null,
  snap: null,
  sys: null,

  tmp: {
    "session.tmp": `SESSION_ID=abc123xyz
STARTED=2024-01-15T10:30:00
USER=user
SHELL=/bin/bash`,
    "notes.tmp": `temporary scratch notes
will be deleted on reboot`,
  },

  usr: {
    bin: null,
    lib: null,
    local: {
      bin: null,
    },
    share: {
      doc: null,
    },
  },

  var: {
    log: {
      "syslog": `Jan 15 10:00:01 labfae systemd[1]: Started Session 1 of user user.
Jan 15 10:00:02 labfae kernel: [    0.000000] Linux version 5.15.0-91-generic
Jan 15 10:00:02 labfae kernel: [    0.000000] BIOS-provided physical RAM map
Jan 15 10:00:05 labfae NetworkManager[892]: <info> eth0: connected
Jan 15 10:01:00 labfae CRON[1234]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
Jan 15 10:15:01 labfae systemd[1]: Starting Daily apt upgrade and clean activities
Jan 15 10:15:03 labfae apt: Unattended upgrade returned: 0
Jan 15 11:00:01 labfae CRON[2345]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
Jan 15 11:30:22 labfae sshd[3456]: Accepted publickey for user from 192.168.1.5 port 52341
Jan 15 11:30:22 labfae systemd[1]: Started Session 2 of user user.
Jan 15 12:00:01 labfae CRON[4567]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)`,

      "auth.log": `Jan 15 10:00:01 labfae sshd[890]: Server listening on 0.0.0.0 port 22.
Jan 15 10:30:11 labfae sshd[1100]: Failed password for invalid user admin from 45.33.32.156 port 49876 ssh2
Jan 15 10:30:14 labfae sshd[1101]: Failed password for invalid user root from 45.33.32.156 port 49877 ssh2
Jan 15 10:30:17 labfae sshd[1102]: Failed password for invalid user ubuntu from 45.33.32.156 port 49878 ssh2
Jan 15 11:30:22 labfae sshd[3456]: Accepted publickey for user from 192.168.1.5 port 52341 ssh2
Jan 15 11:30:22 labfae sshd[3456]: pam_unix(sshd:session): session opened for user user
Jan 15 13:45:01 labfae sudo[5678]: user : TTY=pts/0 ; PWD=/home/user ; USER=root ; COMMAND=/usr/bin/apt update`,

      "dpkg.log": `2024-01-15 09:00:01 startup packages configure
2024-01-15 09:00:02 install libc6:amd64 <none> 2.35-0ubuntu3
2024-01-15 09:00:04 status installed libc6:amd64 2.35-0ubuntu3
2024-01-15 09:00:05 install bash:amd64 <none> 5.1-6ubuntu1
2024-01-15 09:00:07 status installed bash:amd64 5.1-6ubuntu1
2024-01-15 09:00:09 install curl:amd64 <none> 7.81.0-1ubuntu1
2024-01-15 09:00:11 status installed curl:amd64 7.81.0-1ubuntu1`,
    },
    cache: null,
    lib: null,
  },
};

// ─────────────────────────────────────────────
//  SESSION STATE
// ─────────────────────────────────────────────
let state = {
  cwd: "/home/user",
  user: "user",
  hostname: "labfae",
  env: {
    HOME: "/home/user",
    USER: "user",
    SHELL: "/bin/bash",
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    LANG: "en_US.UTF-8",
    EDITOR: "nano",
    TERM: "xterm-256color",
    PWD: "/home/user",
    OLDPWD: "/home/user",
  } as Record<string, string>,
  aliases: {
    ll: "ls -alF",
    la: "ls -A",
    l:  "ls -CF",
    gs: "git status",
  } as Record<string, string>,
  history: [] as string[],
  overlay: {} as Record<string, any>,
  deleted: new Set<string>(),
  protected: new Set<string>(["/root", "/etc/shadow", "/proc/sysrq-trigger"]),
};

// ─────────────────────────────────────────────
//  FILESYSTEM HELPERS
// ─────────────────────────────────────────────

function normalizePath(p: string | undefined): string {
  if (!p) return state.cwd;
  if (p.startsWith("~")) p = state.env.HOME + p.slice(1);
  if (!p.startsWith("/")) p = state.cwd + "/" + p;
  const parts = p.split("/").filter(Boolean);
  const resolved: string[] = [];
  for (const part of parts) {
    if (part === ".") continue;
    if (part === "..") resolved.pop();
    else resolved.push(part);
  }
  return "/" + resolved.join("/");
}

function getNode(absPath: string): FSNode | undefined {
  if (state.deleted.has(absPath)) return undefined;
  if (absPath in state.overlay) return state.overlay[absPath];

  if (absPath === "/") return FILESYSTEM;
  const parts = absPath.split("/").filter(Boolean);
  let node: FSNode = FILESYSTEM;
  for (const part of parts) {
    if (node === null) return undefined;
    if (typeof node === "string") return undefined;
    if (!(part in node)) return undefined;
    node = (node as Record<string, FSNode>)[part];
  }
  return node;
}

function isDir(absPath: string): boolean {
  const node = getNode(absPath);
  return node !== undefined && node !== null && typeof node !== "string";
}

function isFile(absPath: string): boolean {
  const node = getNode(absPath);
  return typeof node === "string";
}

function listDir(absPath: string): string[] | null {
  if (!isDir(absPath)) return null;
  const entries = new Set<string>();
  const node = getNode(absPath);

  if (absPath === "/") {
    Object.keys(FILESYSTEM as Record<string, FSNode>).forEach(k => { if (k) entries.add(k); });
  } else {
    if (node && typeof node === "object") {
      Object.keys(node).forEach(k => entries.add(k));
    }
  }

  const prefix = absPath === "/" ? "/" : absPath + "/";
  for (const p of Object.keys(state.overlay)) {
    if (p.startsWith(prefix)) {
      const rest = p.slice(prefix.length);
      if (!rest.includes("/")) entries.add(rest);
    }
  }

  for (const p of state.deleted) {
    if (p.startsWith(prefix)) {
      const rest = p.slice(prefix.length);
      if (!rest.includes("/")) entries.delete(rest);
    }
  }

  return [...entries].filter(Boolean).sort();
}

function parentPath(absPath: string): string {
  const parts = absPath.split("/").filter(Boolean);
  parts.pop();
  return "/" + parts.join("/");
}

function basename(absPath: string): string {
  return absPath.split("/").filter(Boolean).pop() || "/";
}

// ─────────────────────────────────────────────
//  OUTPUT HELPERS
// ─────────────────────────────────────────────
function out(text: string): CommandResult { return { type: "output", text }; }
function err(text: string): CommandResult { return { type: "error", text }; }
function info(text: string): CommandResult { return { type: "info", text }; }

// ─────────────────────────────────────────────
//  COMMAND HANDLERS
// ─────────────────────────────────────────────

const commands: Record<string, (args: string[], flags: string[], rawArgs: string[]) => CommandResult> = {};

commands.echo = (args, flags) => {
  let text = args.join(" ");
  text = text.replace(/\$([A-Z_][A-Z0-9_]*)/g, (_, name) =>
    state.env[name as string] !== undefined ? state.env[name as string] : ""
  );
  text = text.replace(/\$\(\((.+?)\)\)/g, (_, expr) => {
    try { return String(Function('"use strict"; return (' + expr + ')')()) }
    catch { return "0" }
  });
  text = text.replace(/^["']|["']$/g, "");

  if (flags.includes("-n")) return out(text);
  if (flags.includes("-e")) {
    text = text.replace(/\\n/g, "\n").replace(/\\t/g, "\t");
  }
  return out(text);
};

commands.clear = () => ({ type: "clear" });
commands.pwd = () => out(state.cwd);

commands.cd = (args) => {
  let target = args[0] || state.env.HOME;
  if (target === "-") target = state.env.OLDPWD || state.env.HOME;
  const abs = normalizePath(target);

  if (state.protected.has(abs)) return err(`cd: ${abs}: Permission denied`);

  if (!isDir(abs)) {
    if (isFile(abs)) return err(`cd: ${abs}: Not a directory`);
    return err(`cd: ${args[0]}: No such file or directory`);
  }

  state.env.OLDPWD = state.cwd;
  state.cwd = abs;
  state.env.PWD = abs;
  return null;
};

commands.ls = (args, flags, rawArgs) => {
  const showHidden = flags.includes("-a") || flags.includes("-A");
  const longFormat = flags.includes("-l");
  const recursive = flags.includes("-R");

  const targetArg = args[0] || state.cwd;
  const abs = normalizePath(targetArg);

  if (state.protected.has(abs)) return err(`ls: cannot open directory '${targetArg}': Permission denied`);

  if (isFile(abs)) {
    if (longFormat) return out(formatLong(abs, basename(abs)));
    return out(basename(abs));
  }

  if (!isDir(abs)) return err(`ls: cannot access '${targetArg}': No such file or directory`);

  const entries = listDir(abs) || [];
  const visible = showHidden
    ? (flags.includes("-a") ? [".", "..", ...entries] : entries)
    : entries.filter(e => !e.startsWith("."));

  if (longFormat) {
    const lines = ["total " + visible.length * 4];
    for (const name of visible) {
      const childPath = abs === "/" ? "/" + name : abs + "/" + name;
      lines.push(formatLong(childPath, name));
    }
    return out(lines.join("\n"));
  }

  if (recursive) {
    let output = abs + ":\n" + colorNames(visible, abs).join("  ");
    for (const name of visible.filter(n => !n.startsWith("."))) {
      const childPath = abs === "/" ? "/" + name : abs + "/" + name;
      if (isDir(childPath)) {
        const sub = commands.ls([childPath], flags, rawArgs);
        if (sub && 'text' in sub) output += "\n\n" + (sub.text || "");
      }
    }
    return out(output);
  }

  return out(colorNames(visible, abs).join("  "));
};

function isExecutable(absPath: string): boolean {
  if (absPath.endsWith(".sh")) return true;
  const content = getNode(absPath);
  if (typeof content === "string" && content.startsWith("#!/")) return true;
  return false;
}

function colorNames(names: string[], parentAbs: string): string[] {
  return names.map(name => {
    const childPath = parentAbs === "/" ? "/" + name : parentAbs + "/" + name;
    if (isDir(childPath)) return `\x1b[01;34m${name}\x1b[0m`;
    if (isExecutable(childPath)) return `\x1b[01;32m${name}\x1b[0m`;
    if (/\.(tar|gz|zip|7z|rar|bz2|xz)$/.test(name)) return `\x1b[01;31m${name}\x1b[0m`;
    if (/\.(png|jpg|jpeg|gif|mp4|mkv|webm|svg)$/.test(name)) return `\x1b[01;35m${name}\x1b[0m`;
    if (/\.(mp3|wav|ogg|flac)$/.test(name)) return `\x1b[01;36m${name}\x1b[0m`;
    return name;
  });
}

function formatLong(absPath: string, name: string): string {
  const dir = isDir(absPath);
  const type = dir ? "d" : "-";
  const perms = dir ? "rwxr-xr-x" : "rw-r--r--";
  const size = dir ? "4096" : String(typeof getNode(absPath) === "string" ? (getNode(absPath) as string).length : 0);
  return `${type}${perms}  1 user user ${size.padStart(6)}  Jan 15 10:00  ${name}`;
}

commands.cat = (args, flags) => {
  if (!args.length) return info("cat: reading from stdin (type text then Ctrl+D)");
  const results = [];
  for (const arg of args) {
    const abs = normalizePath(arg);
    if (state.protected.has(abs)) { results.push(`cat: ${arg}: Permission denied`); continue; }
    if (isDir(abs)) { results.push(`cat: ${arg}: Is a directory`); continue; }
    if (!isFile(abs)) { results.push(`cat: ${arg}: No such file or directory`); continue; }
    let content = getNode(abs) as string;
    if (flags.includes("-n")) {
      content = content.split("\n").map((l, i) => `${String(i + 1).padStart(6)}\t${l}`).join("\n");
    }
    results.push(content);
  }
  return out(results.join("\n"));
};

commands.head = (args, flags) => {
  const n = getFlag(flags, "-n") || "10";
  return fileOp(args, content =>
    content.split("\n").slice(0, Number(n)).join("\n")
  );
};

commands.tail = (args, flags) => {
  const n = getFlag(flags, "-n") || "10";
  if (flags.includes("-f")) {
    const res = fileOp(args, c => c.split("\n").slice(-Number(n)).join("\n"));
    return info("tail: -f not supported in simulator (no live files). Showing last lines instead:\n" + (res && 'text' in res ? res.text : ""));
  }
  return fileOp(args, content =>
    content.split("\n").slice(-Number(n)).join("\n")
  );
};

commands.wc = (args, flags) => {
  return fileOp(args, (content, name) => {
    const lines = content.split("\n").length;
    const words = content.trim().split(/\s+/).length;
    const bytes = content.length;
    if (flags.includes("-l")) return `${lines} ${name}`;
    if (flags.includes("-w")) return `${words} ${name}`;
    if (flags.includes("-c")) return `${bytes} ${name}`;
    return `  ${lines}  ${words} ${bytes} ${name}`;
  });
};

commands.grep = (args, flags) => {
  if (!args.length) return err("grep: missing pattern");
  const pattern = args[0];
  const files = args.slice(1);
  const ignoreCase = flags.includes("-i");
  const showLineNums = flags.includes("-n");
  const invertMatch = flags.includes("-v");
  const countOnly = flags.includes("-c");
  const showFiles = flags.includes("-l");

  const regex = new RegExp(pattern, ignoreCase ? "i" : "");

  if (!files.length) return err("grep: no files specified (stdin not supported in simulator)");

  const results = [];
  for (const f of files) {
    const abs = normalizePath(f);
    if (!isFile(abs)) { results.push(`grep: ${f}: No such file or directory`); continue; }
    const lines = (getNode(abs) as string).split("\n");
    const matched = lines
      .map((line, i) => ({ line, i: i + 1, match: regex.test(line) }))
      .filter(({ match }) => invertMatch ? !match : match);

    if (countOnly) { results.push(`${matched.length} ${f}`); continue; }
    if (showFiles && matched.length) { results.push(f); continue; }
    for (const { line, i } of matched) {
      const prefix = files.length > 1 ? f + ":" : "";
      const lineNum = showLineNums ? i + ":" : "";
      results.push(`${prefix}${lineNum}${line}`);
    }
  }
  return results.length ? out(results.join("\n")) : out("");
};

commands.find = (args, flags, rawArgs) => {
  const startArg = args[0] || ".";
  const start = normalizePath(startArg);
  const nameIdx = rawArgs.indexOf("-name");
  const typeIdx = rawArgs.indexOf("-type");
  const namePattern = nameIdx >= 0 ? rawArgs[nameIdx + 1] : null;
  const typeFilter = typeIdx >= 0 ? rawArgs[typeIdx + 1] : null;

  const results: string[] = [];
  function walk(p: string) {
    if (state.deleted.has(p) || state.protected.has(p)) return;
    const entries = listDir(p);
    if (!entries) return;
    for (const name of entries) {
      const child = p === "/" ? "/" + name : p + "/" + name;
      const dir = isDir(child);

      let match = true;
      if (namePattern) {
        const regex = new RegExp("^" + namePattern.replace(/\*/g, ".*").replace(/\?/g, ".") + "$");
        match = match && regex.test(name);
      }
      if (typeFilter === "f") match = match && !dir;
      if (typeFilter === "d") match = match && dir;

      if (match) results.push(child);
      if (dir) walk(child);
    }
  }
  walk(start);
  return results.length ? out(results.join("\n")) : out("");
};

commands.touch = (args) => {
  if (!args.length) return err("touch: missing file operand");
  for (const arg of args) {
    const abs = normalizePath(arg);
    if (!isFile(abs) && !isDir(abs)) {
      state.overlay[abs] = "";
    }
  }
  return null;
};

commands.mkdir = (args, flags) => {
  if (!args.length) return err("mkdir: missing operand");
  for (const arg of args) {
    const abs = normalizePath(arg);
    if (isDir(abs)) return err(`mkdir: cannot create directory '${arg}': File exists`);
    if (!flags.includes("-p")) {
      const parent = parentPath(abs);
      if (!isDir(parent)) return err(`mkdir: cannot create directory '${arg}': No such file or directory`);
    }
    state.overlay[abs] = {};
    if (flags.includes("-v")) return out(`mkdir: created directory '${arg}'`);
  }
  return null;
};

commands.rm = (args, flags) => {
  if (!args.length) return err("rm: missing operand");
  for (const arg of args) {
    const abs = normalizePath(arg);
    if (abs === "/" || abs === "/home" || abs === "/home/user") {
      return err(`rm: refusing to remove '${arg}': this would be bad`);
    }
    if (!isFile(abs) && !isDir(abs)) return err(`rm: cannot remove '${arg}': No such file or directory`);
    if (isDir(abs) && !flags.includes("-r") && !flags.includes("-rf")) {
      return err(`rm: cannot remove '${arg}': Is a directory (use -r)`);
    }
    state.deleted.add(abs);
    delete state.overlay[abs];
  }
  return null;
};

commands.cp = (args, flags) => {
  if (args.length < 2) return err("cp: missing destination operand");
  const [src, dest] = args;
  const absSrc = normalizePath(src);
  const absDest = normalizePath(dest);
  if (!isFile(absSrc)) return err(`cp: cannot stat '${src}': No such file or directory`);
  state.overlay[absDest] = getNode(absSrc);
  if (flags.includes("-v")) return out(`'${src}' -> '${dest}'`);
  return null;
};

commands.mv = (args, flags) => {
  if (args.length < 2) return err("mv: missing destination operand");
  const [src, dest] = args;
  const absSrc = normalizePath(src);
  const absDest = normalizePath(dest);
  const node = getNode(absSrc);
  if (node === undefined) return err(`mv: cannot stat '${src}': No such file or directory`);
  state.overlay[absDest] = node;
  state.deleted.add(absSrc);
  delete state.overlay[absSrc];
  if (flags.includes("-v")) return out(`renamed '${src}' -> '${dest}'`);
  return null;
};

commands.whoami = () => out(state.user);
commands.id = () => out(`uid=1000(${state.user}) gid=1000(${state.user}) groups=1000(${state.user}),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd)`);
commands.who = () => out(`${state.user}   pts/0        2024-01-15 10:00 (:0)`);
commands.w = () => out(` 10:30:01 up 2:30,  1 user,  load average: 0.12, 0.08, 0.05\nUSER     TTY      FROM             LOGIN@   IDLE JCPU   PCPU WHAT\n${state.user}   pts/0    :0               10:00    0.00s 0.05s 0.01s bash`);

commands.hostname = (args, flags) => {
  if (flags.includes("-I")) return out("192.168.1.42 ");
  return out(state.hostname);
};

commands.uname = (args, flags) => {
  if (flags.includes("-a")) return out("Linux labfae 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux");
  if (flags.includes("-r")) return out("5.15.0-91-generic");
  if (flags.includes("-m")) return out("x86_64");
  return out("Linux");
};

commands.printenv = (args) => {
  if (args.length) return out(state.env[args[0]] !== undefined ? state.env[args[0]] : "");
  return out(Object.entries(state.env).map(([k, v]) => `${k}=${v}`).join("\n"));
};
commands.env = () => commands.printenv([], [], []);

commands.export = (args) => {
  for (const arg of args) {
    const [key, ...rest] = arg.split("=");
    if (rest.length) state.env[key] = rest.join("=").replace(/^["']|["']$/g, "");
  }
  return null;
};

commands.alias = (args) => {
  if (!args.length) {
    return out(Object.entries(state.aliases).map(([k, v]) => `alias ${k}='${v}'`).join("\n"));
  }
  for (const arg of args) {
    const eq = arg.indexOf("=");
    if (eq === -1) {
      const v = state.aliases[arg];
      return v ? out(`alias ${arg}='${v}'`) : err(`bash: alias: ${arg}: not found`);
    }
    state.aliases[arg.slice(0, eq)] = arg.slice(eq + 1).replace(/^["']|["']$/g, "");
  }
  return null;
};

commands.history = (args, flags) => {
  if (flags.includes("-c")) { state.history = []; return null; }
  return out(state.history.map((cmd, i) => `  ${String(i + 1).padStart(3)}  ${cmd}`).join("\n"));
};

commands.uptime = () => {
  const d = new Date();
  const t = `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}:${String(d.getSeconds()).padStart(2,"0")}`;
  return out(` ${t} up 2:30,  1 user,  load average: 0.12, 0.08, 0.05`);
};

commands.free = (args, flags) => {
  const h = flags.includes("-h");
  if (h) return out(`               total        used        free      shared  buff/cache   available\nMem:           7.7Gi       2.1Gi       2.2Gi       312Mi       3.3Gi       5.0Gi\nSwap:          2.0Gi          0B       2.0Gi`);
  return out(`               total        used        free      shared  buff/cache   available\nMem:         8048576     2201344     2341256      319488     3505976     4521984\nSwap:        2097152           0     2097152`);
};

commands.df = (args, flags) => {
  const h = flags.includes("-h");
  if (h) return out(`Filesystem      Size  Used Avail Use% Mounted on\ntmpfs           785M  1.5M  784M   1% /run\n/dev/sda1        40G   12G   26G  32% /\ntmpfs           3.9G     0  3.9G   0% /dev/shm\ntmpfs           5.0M  4.0K  5.0M   1% /run/lock\n/dev/sda2       512M   6.1M  506M   2% /boot/efi\ntmpfs           785M   84K  785M   1% /run/user/1000`);
  return out(`Filesystem     1K-blocks    Used Available Use% Mounted on\ntmpfs             803832    1536    802296   1% /run\n/dev/sda1       41921536 12345678  27560858  32% /\ntmpfs            4019152       0   4019152   0% /dev/shm`);
};

commands.du = (args, flags) => {
  const h = flags.includes("-h");
  const s = flags.includes("-s");
  const target = args[0] || ".";
  if (s) return out(h ? `48K\t${target}` : `48\t${target}`);
  return out(h
    ? `4.0K\t${target}/Desktop\n8.0K\t${target}/Documents\n4.0K\t${target}/Downloads\n16K\t${target}/Projects\n48K\t${target}`
    : `4\t${target}/Desktop\n8\t${target}/Documents\n4\t${target}/Downloads\n16\t${target}/Projects\n48\t${target}`
  );
};

commands.ps = (args, flags) => {
  const all = args.includes("aux") || flags.includes("-e") || flags.includes("-ef");
  if (all) return out(`USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\nroot           1  0.0  0.1 169568 13312 ?        Ss   10:00   0:01 /sbin/init\nroot         892  0.0  0.0  13672  7424 ?        Ss   10:00   0:00 sshd: /usr/sbin/sshd\nroot        1234  0.0  0.1  14732  9216 ?        Ss   10:00   0:00 /usr/sbin/cron\n${state.user}       2001  0.0  0.1  10492  5248 pts/0    Ss   10:30   0:00 bash\n${state.user}       2099  0.0  0.0   7672  3328 pts/0    R+   10:31  0:00 ps aux`);
  return out(`    PID TTY          TIME CMD\n   2001 pts/0    00:00:00 bash\n   2099 pts/0    00:00:00 ps`);
};

commands.ping = (args, flags) => {
  const host = args[0] || "localhost";
  const count = getFlag(flags, "-c") || "4";
  const lines = [`PING ${host} (93.184.216.34) 56(84) bytes of data.`];
  for (let i = 0; i < Math.min(Number(count), 4); i++) {
    const ms = (10 + Math.random() * 20).toFixed(3);
    lines.push(`64 bytes from ${host} (93.184.216.34): icmp_seq=${i+1} ttl=55 time=${ms} ms`);
  }
  lines.push(`\n--- ${host} ping statistics ---`);
  lines.push(`${count} packets transmitted, ${count} received, 0% packet loss, time ${Number(count)*1000}ms`);
  return out(lines.join("\n"));
};

commands.ip = (args) => {
  if (args[0] === "addr" || args[0] === "a") {
    return out(`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN\n    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00\n    inet 127.0.0.1/8 scope host lo\n2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP\n    link/ether 08:00:27:ab:cd:ef brd ff:ff:ff:ff:ff:ff\n    inet 192.168.1.42/24 brd 192.168.1.255 scope global dynamic eth0`);
  }
  if (args[0] === "route" || args[0] === "r") {
    return out(`default via 192.168.1.1 dev eth0 proto dhcp src 192.168.1.42 metric 100\n192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.42`);
  }
  return out("Usage: ip addr | ip route | ip link");
};

commands.sort = (args, flags) => {
  return fileOp(args, content => {
    let lines = content.split("\n");
    if (flags.includes("-r")) lines.reverse();
    else if (flags.includes("-n")) lines.sort((a, b) => parseFloat(a) - parseFloat(b));
    else lines.sort();
    if (flags.includes("-u")) lines = [...new Set(lines)];
    return lines.join("\n");
  });
};

commands.uniq = (args, flags) => {
  return fileOp(args, content => {
    const lines = content.split("\n");
    if (flags.includes("-c")) {
      const result = [];
      let last: string | null = null, count = 0;
      for (const l of lines) {
        if (l === last) count++;
        else { if (last !== null) result.push(`${String(count).padStart(4)} ${last}`); last = l; count = 1; }
      }
      if (last !== null) result.push(`${String(count).padStart(4)} ${last}`);
      return result.join("\n");
    }
    return lines.filter((l, i) => i === 0 || l !== lines[i - 1]).join("\n");
  });
};

commands.cut = (args, flags, rawArgs) => {
  const dIdx = rawArgs.indexOf("-d");
  const fIdx = rawArgs.indexOf("-f");
  const delim = dIdx >= 0 ? rawArgs[dIdx + 1] : "\t";
  const field = fIdx >= 0 ? parseInt(rawArgs[fIdx + 1]) - 1 : 0;
  return fileOp(args.filter(a => !a.startsWith("-")), content =>
    content.split("\n").map(l => l.split(delim)[field] || "").join("\n")
  );
};

commands.tr = (args) => {
  if (args.length < 2) return err("tr: missing operand");
  return info("tr: pipe input not supported in simulator. Example: echo 'hello' | tr 'a-z' 'A-Z' → HELLO");
};

commands.which = (args) => {
  const known = ["ls","cd","pwd","echo","cat","grep","find","sort","head","tail","wc","bash","sh","python3","git","docker","curl","wget","nano","vim","ssh"];
  const results = args.map(a => known.includes(a) ? `/usr/bin/${a}` : `${a}: not found`);
  return out(results.join("\n"));
};

commands.whereis = (args) => {
  if (!args.length) return err("whereis: missing argument");
  return out(`${args[0]}: /usr/bin/${args[0]} /usr/share/man/man1/${args[0]}.1.gz`);
};

commands.type = (args, flags) => {
  const builtins = ["cd","echo","alias","export","history","type","exit","help"];
  return out(args.map(a => {
    if (builtins.includes(a)) return `${a} is a shell builtin`;
    if (state.aliases[a]) return `${a} is aliased to '${state.aliases[a]}'`;
    return `${a} is /usr/bin/${a}`;
  }).join("\n"));
};

commands.man = (args) => {
  if (!args.length) return err("What manual page do you want?");
  const cmd = args[0];
  return out(`MAN PAGE: ${cmd.toUpperCase()}(1)\n\nNAME\n    ${cmd} - simulate the ${cmd} command\n\nSYNOPSIS\n    ${cmd} [OPTION]... [FILE]...\n\nDESCRIPTION\n    This is a simulated man page for the ${cmd} command.\n    For full documentation, run this command on a real Linux system.\n\n    Use 'tldr ${cmd}' for quick practical examples.\n    Press q to quit (in real terminal).\n\nSEE ALSO\n    info ${cmd}, ${cmd} --help`);
};

commands.whatis = (args) => {
  const db: Record<string, string> = {
    ls: "ls (1) - list directory contents",
    cd: "cd (1) - change the shell working directory",
    pwd: "pwd (1) - print name of current/working directory",
    grep: "grep (1) - print lines that match patterns",
    cat: "cat (1) - concatenate files and print on the standard output",
    echo: "echo (1) - display a line of text",
    find: "find (1) - search for files in a directory hierarchy",
    man: "man (1) - an interface to the system reference manuals",
    chmod: "chmod (1) - change file mode bits",
    sudo: "sudo (8) - execute a command as another user",
  };
  return out(args.map(a => db[a] || `${a}: nothing appropriate.`).join("\n"));
};

commands.apropos = (args) => {
  if (!args.length) return err("apropos: missing argument");
  return out(`grep (1)           - print lines that match patterns\negrep (1)          - print lines that match patterns (extended)\nfgrep (1)          - print lines that match patterns (fixed string)\nzgrep (1)          - search possibly compressed files for a regular expression`);
};

commands.chmod = (args, flags) => {
  if (args.length < 2) return err("chmod: missing operand");
  if (flags.includes("-v")) return out(`mode of '${args[1]}' changed to ${args[0]}`);
  return null;
};

commands.chown = (args) => {
  if (args.length < 2) return err("chown: missing operand");
  return null;
};

commands.ln = (args, flags) => {
  if (args.length < 2) return err("ln: missing file operand");
  const [src, dest] = args;
  const absSrc = normalizePath(src);
  const absDest = normalizePath(dest);
  if (!isFile(absSrc) && !isDir(absSrc)) return err(`ln: failed to access '${src}': No such file or directory`);
  state.overlay[absDest] = getNode(absSrc);
  return null;
};

commands.file = (args, flags) => {
  if (!args.length) return err("file: missing operand");
  return out(args.map(a => {
    const abs = normalizePath(a);
    if (isDir(abs)) return `${a}: directory`;
    if (!isFile(abs)) return `${a}: ERROR: No such file or directory`;
    const content = getNode(abs) as string;
    if (content.startsWith("#!/bin/bash") || content.startsWith("#!/bin/sh")) return `${a}: Bourne-Again shell script, ASCII text executable`;
    if (a.endsWith(".txt") || a.endsWith(".md")) return `${a}: ASCII text`;
    if (a.endsWith(".pdf")) return `${a}: PDF document, version 1.6`;
    return `${a}: ASCII text`;
  }).join("\n"));
};

commands.stat = (args) => {
  if (!args.length) return err("stat: missing operand");
  const abs = normalizePath(args[0]);
  if (!isFile(abs) && !isDir(abs)) return err(`stat: cannot stat '${args[0]}': No such file or directory`);
  const size = isFile(abs) ? (getNode(abs) as string).length : 4096;
  return out(`  File: ${args[0]}\n  Size: ${size}       Blocks: 8          IO Block: 4096   ${isDir(abs) ? "directory" : "regular file"}\nDevice: 801h/2049d    Inode: 131073      Links: 1\nAccess: (0644/-rw-r--r--)  Uid: ( 1000/   ${state.user})   Gid: ( 1000/   ${state.user})\nAccess: 2024-01-15 10:00:00.000000000 +0000\nModify: 2024-01-15 10:00:00.000000000 +0000\nChange: 2024-01-15 10:00:00.000000000 +0000\n Birth: 2024-01-15 10:00:00.000000000 +0000`);
};

commands.tree = (args, flags) => {
  const targetArg = args[0] || ".";
  const abs = normalizePath(targetArg);
  if (!isDir(abs)) return err(`tree: '${targetArg}': not a directory`);
  const showHidden = flags.includes("-a");
  const dirOnly = flags.includes("-d");

  let fileCount = 0, dirCount = 0;

  function buildTree(p: string, prefix: string): string {
    const entries = listDir(p) || [];
    const visible = showHidden ? entries : entries.filter(e => !e.startsWith("."));
    let result = "";
    
    visible.forEach((name, i) => {
      const childPath = p === "/" ? "/" + name : p + "/" + name;
      const isLast = i === visible.length - 1;
      const connector = isLast ? "└── " : "├── ";
      const childIsDir = isDir(childPath);
      
      if (dirOnly && !childIsDir) return;
      
      const coloredName = childIsDir ? `\x1b[01;34m${name}\x1b[0m` : name;
      result += prefix + connector + coloredName + "\n";
      
      if (childIsDir) { 
        dirCount++; 
        result += buildTree(childPath, prefix + (isLast ? "    " : "│   ")); 
      } else {
        fileCount++;
      }
    });
    return result;
  }

  const rootName = basename(abs);
  const output = `\x1b[01;34m${rootName}\x1b[0m\n` + buildTree(abs, "");
  return out(output + `\n${dirCount} director${dirCount === 1 ? "y" : "ies"}, ${fileCount} file${fileCount === 1 ? "" : "s"}`);
};

commands.nano = (args) => {
  if (!args.length) return err("nano: filename missing");
  const filename = args[0];
  const abs = normalizePath(filename);
  
  if (isDir(abs)) return err(`nano: ${filename}: Is a directory`);
  if (!isFile(abs)) {
    state.overlay[abs] = ""; // Create empty file if it doesn't exist
  }
  
  const content = (getNode(abs) as string) || "";
  return { type: "nano", filename, absPath: abs, content };
};

commands.download = (args) => {
  if (!args.length) return err("download: missing filename");
  const filename = args[0];
  const abs = normalizePath(filename);
  if (!isFile(abs)) return err(`download: ${filename}: No such file or directory`);
  const content = (getNode(abs) as string) || "";
  return { type: "download", filename, content };
};

commands.export = () => {
  return { type: "export" };
};

commands.neofetch = () => {
  return out(`\x1b[01;32muser@labfae\x1b[0m
-----------------
OS: Ubuntu 22.04.3 LTS x86_64
Host: TechFairy Academy
Kernel: 5.15.0-91-generic
Uptime: 2 hours, 30 mins
Packages: 1834 (dpkg)
Shell: bash 5.1.16
Resolution: 1920x1080
Terminal: InteractiveTerminal
CPU: Intel i5-8250U (4) @ 1.60GHz
GPU: NVIDIA GeForce GTX 1060
Memory: 2341MiB / 8048MiB`);
};

commands.cowsay = (args) => {
  const message = args.join(" ") || "Moo!";
  const top = " " + "_".repeat(message.length + 2);
  const bottom = " " + "-".repeat(message.length + 2);
  return out(`${top}\n< ${message} >\n${bottom}
        \\   ^__^
         \\  (oo)\\_______
            (__)\\       )\\/\\
                ||----w |
                ||     ||`);
};

commands.sl = () => {
  return out(`      ====        ________                ___________
  _D _|  |_______/        \\__I_I_____===__|_________|
   |(_)---  |   H\\________/ |   |        =|___ ___|
   /     |  |   H  |  |     |   |         ||_| |_|
  |      |  |   H  |__--------------------| [___] |
  | ________|___H__/__|_____/[][]~\\_______|       |
  |/ |   |-----------I_____I [][] []  D   |=======|__
__/ =| o |=-~~\\  /~~\\  /~~\\  /~~\\ ____Y___________|__
 |/-=|___|=O=====O=====O=====O   |_____/~\\___/
  \\_/      \\__/  \\__/  \\__/  \\__/      \\_/`);
};

commands.fortune = () => {
  const fortunes = [
    "Today is a good day to code! 💻",
    "The best way to predict the future is to implement it.",
    "Code is poetry written for machines to understand.",
    "Every expert was once a beginner. Keep coding! 🚀",
    "Talk is cheap. Show me the code. - Linus Torvalds"
  ];
  return out(`💫 ${fortunes[Math.floor(Math.random() * fortunes.length)]}`);
};

commands.git = (args) => {
  const sub = args[0];
  if (!sub) return out(`usage: git [--version] [--help] <command> [<args>]\n\nCommon commands:\n  init      Create empty repository\n  status    Show working tree status\n  add       Add file contents to index\n  commit    Record changes to repository\n  log       Show commit logs\n  branch    List branches\n  diff      Show changes`);

  if (sub === "status") return out(`On branch main\nYour branch is up to date with 'origin/main'.\n\nChanges not staged for commit:\n  (use "git add <file>..." to update what will be committed)\n\n\tmodified:   hello.sh\n\nUntracked files:\n  (use "git add <file>..." to include in what will be committed)\n\n\tcount.sh\n\nnothing added to commit but untracked files present`);

  if (sub === "log") return out(`commit a3f8c2d1b4e5f6789012345678901234567890ab (HEAD -> main, origin/main)\nAuthor: user <user@labfae.com>\nDate:   Mon Jan 15 10:00:00 2024 +0000\n\n    Add hello world script\n\ncommit 1b2c3d4e5f6789012345678901234567890abcde\nAuthor: user <user@labfae.com>\nDate:   Sun Jan 14 20:00:00 2024 +0000\n\n    Initial commit`);

  if (sub === "branch") return out(`* main\n  dev`);
  if (sub === "init") return out(`Initialized empty Git repository in ${state.cwd}/.git/`);
  if (sub === "add") return null;
  if (sub === "diff") return out(`diff --git a/hello.sh b/hello.sh\nindex abc1234..def5678 100644\n--- a/hello.sh\n+++ b/hello.sh\n@@ -1,3 +1,4 @@\n #!/bin/bash\n echo "Hello, World!"\n+echo "Welcome to bash scripting"`);
  if (sub === "commit") {
    const mIdx = args.indexOf("-m");
    const msg = mIdx >= 0 ? args[mIdx + 1] : "update";
    return out(`[main a3f8c2d] ${msg}\n 1 file changed, 1 insertion(+)`);
  }
  return info(`git ${sub}: simulated — no actual changes made`);
};

commands.sudo = (args) => {
  if (!args.length) return err("usage: sudo <command>");
  return info(`[sudo] password for ${state.user}: \n(Password accepted in simulator)\nRunning: ${args.join(" ")}`);
};

commands.apt = (args) => {
  const sub = args[0];
  if (sub === "update") return out(`Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease\nHit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease\nReading package lists... Done`);
  if (sub === "upgrade") return out(`Reading package lists... Done\nBuilding dependency tree... Done\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`);
  if (sub === "install") return out(`Reading package lists... Done\nBuilding dependency tree... Done\nThe following NEW packages will be installed: ${args.slice(1).join(" ")}\n0 upgraded, ${args.slice(1).length} newly installed\nSetting up ${args.slice(1).join(", ")} ...`);
  return info("apt: simulated — no actual packages installed");
};

commands.exit = () => ({ type: "exit", text: "logout" });

commands.help = () => out(`TechFairy Lab Terminal — Available Commands\n\nNAVIGATION       READING FILES     FILES & DIRS\n  pwd              cat               touch\n  ls               head              mkdir\n  cd               tail              cp\n  tree             wc                mv\n                   grep              rm\nSYSTEM                              ln\n  whoami         TEXT               file\n  id             sort               stat\n  who            uniq\n  uptime         cut              GIT\n  free                             git init\n  df             NETWORK           git status\n  du             ping              git log\n  ps             ip                git add\n  hostname       hostname          git commit\n  uname\n               ENVIRONMENT      OTHER\n               printenv           echo\n               export             man\n               alias              which\n               history            whereis\n                                  sudo\n                                  help\n                                  clear\n                                  exit`);

commands.lsblk = () => out(`NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS\nsda      8:0    0   40G  0 disk\n├─sda1   8:1    0 39.5G  0 part /\n└─sda2   8:2    0  512M  0 part /boot/efi`);

commands.passwd = () => out(`Changing password for ${state.user}.\nCurrent password: (simulator — skipped)\nNew password set successfully.`);

commands.source = (args) => {
  if (!args.length) return err("source: missing filename");
  const abs = normalizePath(args[0]);
  if (!isFile(abs)) return err(`bash: ${args[0]}: No such file or directory`);
  return out(`Sourced ${args[0]}`);
};

commands.nl = (args, flags) => {
  return fileOp(args, content =>
    content.split("\n").map((l, i) => `${String(i + 1).padStart(6)}\t${l}`).join("\n")
  );
};

commands.rmdir = (args) => {
  if (!args.length) return err("rmdir: missing operand");
  for (const arg of args) {
    const abs = normalizePath(arg);
    if (!isDir(abs)) return err(`rmdir: failed to remove '${arg}': No such file or directory`);
    const entries = listDir(abs) || [];
    if (entries.length) return err(`rmdir: failed to remove '${arg}': Directory not empty`);
    state.deleted.add(abs);
    delete state.overlay[abs];
  }
  return null;
};

commands.printf = (args) => {
  if (!args.length) return err("printf: missing format string");
  let fmt = args[0].replace(/\\n/g, "\n").replace(/\\t/g, "\t");
  const rest = args.slice(1);
  let i = 0;
  fmt = fmt.replace(/%s/g, () => rest[i++] || "").replace(/%d/g, () => String(parseInt(rest[i++])) || "0");
  return out(fmt);
};

commands.date = () => out(new Date().toString());

commands.curl = (args) => {
  const url = args.find(a => a.startsWith("http"));
  if (!url) return err("curl: no URL specified");
  return info(`curl: Simulated — network not available in simulator.\nWould have fetched: ${url}`);
};
commands.wget = (args) => {
  const url = args.find(a => a.startsWith("http"));
  if (!url) return err("wget: no URL specified");
  return info(`wget: Simulated — network not available in simulator.\nWould have downloaded: ${url}`);
};

commands.ssh = (args) => {
  return info(`ssh: Network commands are not simulated.\nIn a real terminal:\n  ssh ${args.join(" ")}`);
};

commands.docker = (args) => {
  const sub = args[0];
  if (sub === "ps") return out(`CONTAINER ID   IMAGE     COMMAND       CREATED        STATUS        PORTS      NAMES\na1b2c3d4e5f6   nginx     "nginx -g…"   2 hours ago    Up 2 hours    0.0.0.0:80->80/tcp   web`);
  if (sub === "images") return out(`REPOSITORY   TAG       IMAGE ID       CREATED        SIZE\nnginx        latest    a99a39d070bf   2 weeks ago    142MB\nubuntu       22.04     3b418d7b466a   4 weeks ago    77.8MB`);
  return info(`docker ${sub || ""}: Docker simulation — no daemon running`);
};

commands.systemctl = (args) => {
  const sub = args[0];
  const svc = args[1] || "service";
  if (sub === "status") return out(`● ${svc}.service - ${svc} service\n     Loaded: loaded (/lib/systemd/system/${svc}.service; enabled)\n     Active: active (running) since Mon 2024-01-15 10:00:00 UTC; 2h ago\n   Main PID: 892 (${svc})\n      Tasks: 1 (limit: 4614)\n     Memory: 5.2M\n        CPU: 120ms`);
  return info(`systemctl ${sub} ${svc}: simulated`);
};

// ─────────────────────────────────────────────
//  PIPE SUPPORT  (cmd1 | cmd2)
// ─────────────────────────────────────────────
function executePipe(left: string, right: string): CommandResult {
  const leftResult = executeSingle(left);
  if (!leftResult || leftResult.type === "error") return leftResult;

  const { cmd, args, flags, rawArgs } = parseCommand(right.trim());
  const handler = commands[cmd];
  if (!handler) return err(`bash: ${cmd}: command not found`);

  const tempPath = "/__pipe_input__";
  state.overlay[tempPath] = (leftResult as any).text || "";
  
  const fileOpResult = fileOp([tempPath], content => {
    state.overlay[tempPath] = content;
    return; // returning void instead of null
  });

  let result: CommandResult = null;
  if (cmd === "grep") result = handler([args[0], tempPath], flags, rawArgs);
  else if (cmd === "sort" || cmd === "wc" || cmd === "head" || cmd === "tail" || cmd === "uniq" || cmd === "nl") result = handler([tempPath], flags, rawArgs);
  else if (cmd === "cut") result = handler([...rawArgs.filter(a => !a.startsWith("-")), tempPath], flags, rawArgs);
  else result = info(`Pipe to '${cmd}' is partially simulated`);
  
  delete state.overlay[tempPath];
  return result;
}

// ─────────────────────────────────────────────
//  REDIRECTION SUPPORT  (> and >>)
// ─────────────────────────────────────────────
function executeRedirect(cmdStr: string, file: string, append: boolean): CommandResult {
  const result = executeSingle(cmdStr.trim());
  if (!result || result.type === "error") return result;
  const abs = normalizePath(file.trim());
  const content = (result as any).text || "";
  if (append) {
    const existing = isFile(abs) ? (getNode(abs) as string) : "";
    state.overlay[abs] = existing + content + "\n";
  } else {
    state.overlay[abs] = content + "\n";
  }
  return out(`Output written to ${file.trim()}`);
}

// ─────────────────────────────────────────────
//  COMMAND PARSER
// ─────────────────────────────────────────────
function parseCommand(input: string) {
  const firstWord = input.trim().split(/\s+/)[0];
  if (state.aliases[firstWord]) {
    input = state.aliases[firstWord] + input.slice(firstWord.length);
  }

  const tokens: string[] = [];
  let current = "";
  let inSingle = false, inDouble = false;
  for (let i = 0; i < input.length; i++) {
    const c = input[i];
    if (c === "'" && !inDouble) { inSingle = !inSingle; continue; }
    if (c === '"' && !inSingle) { inDouble = !inDouble; continue; }
    if (c === " " && !inSingle && !inDouble) {
      if (current) { tokens.push(current); current = ""; }
    } else {
      current += c;
    }
  }
  if (current) tokens.push(current);

  const [cmd, ...rest] = tokens;
  const flags = rest.filter(t => t.startsWith("-"));
  const args = rest.filter(t => !t.startsWith("-"));

  return { cmd, args, flags, rawArgs: rest };
}

// ─────────────────────────────────────────────
//  SINGLE COMMAND EXECUTOR
// ─────────────────────────────────────────────
function executeSingle(input: string): CommandResult {
  const { cmd, args, flags, rawArgs } = parseCommand(input);
  if (!cmd) return null;

  const handler = commands[cmd];
  if (!handler) {
    if (cmd.startsWith("./")) {
      const abs = normalizePath(cmd.slice(2));
      if (isFile(abs)) return out((getNode(abs) as string).split("\n").filter(l => !l.startsWith("#") && l.trim()).map(l => {
        if (l.startsWith("echo ")) return l.replace(/^echo /, "").replace(/["']/g, "");
        return "";
      }).filter(Boolean).join("\n"));
      return err(`bash: ${cmd}: No such file or directory`);
    }
    return err(`bash: ${cmd}: command not found`);
  }

  return handler(args, flags, rawArgs);
}

// ─────────────────────────────────────────────
//  MAIN EXECUTE FUNCTION
// ─────────────────────────────────────────────
export function executeCommand(input: string): CommandResult {
  const trimmed = input.trim();
  if (!trimmed) return null;

  state.history.push(trimmed);

  if (trimmed.includes("|")) {
    const parts = trimmed.split("|");
    let result: CommandResult = null;
    for (let i = 0; i < parts.length; i++) {
      if (i === 0) result = executeSingle(parts[0].trim());
      else {
        const tempPath = "/__pipe__";
        if (result && 'text' in result) state.overlay[tempPath] = result.text;
        const { cmd, args, flags, rawArgs } = parseCommand(parts[i].trim());
        const handler = commands[cmd];
        if (!handler) { result = err(`bash: ${cmd}: command not found`); break; }
        const newArgs = (result && 'text' in result) ? [...args, tempPath] : args;
        result = handler(newArgs, flags, rawArgs);
        delete state.overlay[tempPath];
      }
    }
    return result;
  }

  if (trimmed.includes(">>")) {
    const [left, right] = trimmed.split(">>", 2);
    return executeRedirect(left, right, true);
  }

  if (trimmed.includes(">") && !trimmed.includes("2>")) {
    const [left, right] = trimmed.split(">", 2);
    return executeRedirect(left, right, false);
  }

  const cmd2null = trimmed.replace(/\s+2>\/dev\/null/, "").replace(/\s+2>&1/, "");
  return executeSingle(cmd2null);
}

// ─────────────────────────────────────────────
//  TAB AUTOCOMPLETION
// ─────────────────────────────────────────────
export function getCompletions(input: string): string[] {
  const parts = input.trim().split(/\s+/);
  const cmd = parts[0];
  
  if (parts.length === 1) {
    return Object.keys(commands).filter(c => c.startsWith(cmd));
  }

  if (["ls", "cd", "cat", "rm", "mkdir", "touch", "nano"].includes(cmd)) {
    const currentArg = parts[parts.length - 1];
    const absPath = normalizePath(currentArg);
    const parentDir = currentArg.endsWith("/") ? absPath : parentPath(absPath);
    
    if (isDir(parentDir)) {
      const entries = listDir(parentDir) || [];
      const partialName = basename(absPath);
      return entries.filter(e => e.startsWith(partialName));
    }
  }
  
  return [];
}

// ─────────────────────────────────────────────
//  NANO / DOWNLOAD HELPERS
// ─────────────────────────────────────────────
export function saveFileContent(absPath: string, content: string): void {
  state.overlay[absPath] = content;
}

export function getAllSimulatedFiles(): { name: string, content: string }[] {
  const files: { name: string, content: string }[] = [];
  function walk(p: string, prefix: string) {
    const entries = listDir(p) || [];
    for (const name of entries) {
      const childPath = p === "/" ? "/" + name : p + "/" + name;
      const displayPath = prefix ? `${prefix}/${name}` : name;
      if (isFile(childPath)) {
        files.push({ name: displayPath, content: (getNode(childPath) as string) || "" });
      } else if (isDir(childPath)) {
        walk(childPath, displayPath);
      }
    }
  }
  walk("/", "");
  return files;
}

// ─────────────────────────────────────────────
//  PROMPT STRING
// ─────────────────────────────────────────────
export function getPrompt(): string {
  const home = state.env.HOME;
  const displayCwd = state.cwd.startsWith(home)
    ? "~" + state.cwd.slice(home.length)
    : state.cwd;
  return `${state.user}@${state.hostname}:${displayCwd}$`;
}

export function getUser(): string { return state.user; }
export function setUser(name: string): void { state.user = name; state.env.USER = name; }

export function resetSession(): void {
  state.cwd = "/home/user";
  state.env.PWD = "/home/user";
  state.env.OLDPWD = "/home/user";
  state.overlay = {};
  state.deleted = new Set();
  state.history = [];
}

// ─────────────────────────────────────────────
//  HELPERS
// ─────────────────────────────────────────────
function fileOp(args: string[], fn: (content: string, name: string) => string | void): CommandResult {
  if (!args.length) return err("missing file operand");
  const results: string[] = [];
  for (const arg of args) {
    if (arg.startsWith("-")) continue;
    const abs = normalizePath(arg);
    if (state.protected.has(abs)) { results.push(`${arg}: Permission denied`); continue; }
    if (isDir(abs)) { results.push(`${arg}: Is a directory`); continue; }
    if (!isFile(abs)) { results.push(`${arg}: No such file or directory`); continue; }
    const result = fn(getNode(abs) as string, arg);
    if (typeof result === "string") results.push(result);
  }
  return out(results.join("\n---\n"));
}

function getFlag(flags: string[], name: string): string | null {
  const idx = flags.indexOf(name);
  if (idx === -1) return null;
  return flags[idx + 1] || null;
}