import { CommandDef } from "./CommandDef";

export const linuxCmdsTextProcessingFormat: CommandDef[] = [
  {
    name: "colordiff",
    description: "A tool to colorize diff output.",
    useCases: ["View file differences with syntax highlighting"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-u": { description: "Output in unified format" },
      "-y": { description: "Output in side-by-side format" },
    },
    exampleOutputLines: [],
    relatedCommands: ["diff", "delta"],
    category: "text-processing",
  },
  {
    name: "delta",
    description: "A viewer for git and diff output with syntax highlighting.",
    useCases: ["Improve the appearance of git diffs in the terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--side-by-side": { description: "Display diffs side-by-side" },
    },
    exampleOutputLines: [],
    relatedCommands: ["diff", "colordiff"],
    category: "text-processing",
  },
  {
    name: "wdiff",
    description: "Compare two files word by word.",
    useCases: ["Find word-level changes in text documents"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-s": { description: "Print statistics about the differences" },
    },
    exampleOutputLines: [],
    relatedCommands: ["diff", "sdiff"],
    category: "text-processing",
  },
  {
    name: "sdiff",
    description: "Side-by-side merge of file differences.",
    useCases: ["Interactively merge two versions of a file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-s": { description: "Do not print common lines" },
      "-o": { description: "Operate interactively, sending output to a file" },
    },
    exampleOutputLines: [],
    relatedCommands: ["diff", "wdiff"],
    category: "text-processing",
  },
  {
    name: "bat",
    description: "A cat clone with syntax highlighting and Git integration.",
    useCases: ["View source code files with syntax highlighting"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-p": { description: "Print without grid and line numbers" },
      "-l": { description: "Explicitly set the language for syntax highlighting" },
      "--style": { description: "Customize output appearance (e.g., numbers, grid, header)" },
      "-n": { description: "Show line numbers (alias for --style=numbers)" }
    },
    exampleOutputLines: [],
    relatedCommands: ["cat", "less"],
    category: "text-processing",
  },
  {
    name: "highlight",
    description: "Convert source code to formatted text with syntax highlighting.",
    useCases: ["Generate colored HTML or ANSI text from source code"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-O": { description: "Specify the output format (e.g., html, ansi)" },
    },
    exampleOutputLines: [],
    relatedCommands: ["bat"],
    category: "text-processing",
  },
  {
    name: "figlet",
    description: "Display large ASCII art characters.",
    useCases: ["Create text banners in the terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-f": { description: "Select a specific font file" },
      "-c": { description: "Center the output horizontally" },
    },
    exampleOutputLines: [],
    relatedCommands: ["toilet", "banner"],
    category: "text-processing",
  },
  {
    name: "toilet",
    description: "Display large colorful characters.",
    useCases: ["Create colored ASCII art text banners"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-f": { description: "Select the font" },
      "--metal": { description: "Apply a metallic color filter" },
    },
    exampleOutputLines: [],
    relatedCommands: ["figlet"],
    category: "text-processing",
  },
  {
    name: "cowsay",
    description: "Generate an ASCII picture of a cow with a message.",
    useCases: ["Add humor to shell scripts and login messages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-f": { description: "Specify a different animal or character" },
    },
    exampleOutputLines: [],
    relatedCommands: ["fortune"],
    category: "text-processing",
  },
  {
    name: "lolcat",
    description: "Output text in a rainbow gradient.",
    useCases: ["Add rainbow colors to command line output"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-a": { description: "Animate the rainbow colors" },
    },
    exampleOutputLines: [],
    relatedCommands: ["toilet"],
    category: "text-processing",
  },
  {
    name: "fortune",
    description: "Print a random, hopefully interesting, adage.",
    useCases: ["Display a random quote on terminal startup"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-s": { description: "Short fortunes only" },
    },
    exampleOutputLines: [],
    relatedCommands: ["cowsay"],
    category: "text-processing",
  },
  {
    name: "banner",
    description: "Print large text banners on standard output.",
    useCases: ["Create simple large text across the terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["figlet"],
    category: "text-processing",
  },
  {
    name: "boxes",
    description: "Draw ASCII art boxes around text.",
    useCases: ["Add decorative borders to text or source code comments"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Specify the box design to use" },
    },
    exampleOutputLines: [],
    relatedCommands: ["figlet"],
    category: "text-processing",
  },
  {
    name: "pandoc",
    description: "Universal document converter.",
    useCases: ["Convert Markdown to PDF", "Convert HTML to Word"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-o": { description: "Specify the output file" },
      "-f": { description: "Specify the input format" },
      "-t": { description: "Specify the output format" },
    },
    exampleOutputLines: [],
    relatedCommands: ["html2text"],
    category: "text-processing",
  },
  {
    name: "html2text",
    description: "Advanced HTML-to-text converter.",
    useCases: ["Read HTML formatted emails or web pages in the terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-width": { description: "Set screen width" },
    },
    exampleOutputLines: [],
    relatedCommands: ["pandoc"],
    category: "text-processing",
  },
  {
    name: "pdftotext",
    description: "Portable Document Format (PDF) to text converter.",
    useCases: ["Extract raw text content from PDF files for searching"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-layout": { description: "Maintain original physical layout of the text" },
    },
    exampleOutputLines: [],
    relatedCommands: ["pandoc"],
    category: "text-processing",
  },
  {
    name: "enscript",
    description: "Convert text files to PostScript, HTML, RTF, or ANSI.",
    useCases: ["Prepare source code or text for printing with syntax highlighting"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-G": { description: "Print a gaudy header" },
      "--color": { description: "Produce color output" },
    },
    exampleOutputLines: [],
    relatedCommands: ["a2ps"],
    category: "text-processing",
  },
  {
    name: "groff",
    description: "Front-end for the groff document formatting system.",
    useCases: ["Format man pages into readable text or PDF"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-T": { description: "Set the output device (e.g., utf8, pdf)" },
    },
    exampleOutputLines: [],
    relatedCommands: ["nroff", "troff"],
    category: "text-processing",
  },
  {
    name: "a2ps",
    description: "Format files for printing on a PostScript printer.",
    useCases: ["Pretty-print text files or code to PostScript"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-R": { description: "Print in portrait mode" },
    },
    exampleOutputLines: [],
    relatedCommands: ["enscript"],
    category: "text-processing",
  },
  {
    name: "rst2html",
    description: "Convert reStructuredText documents to HTML.",
    useCases: ["Render Python documentation source files as HTML"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["pandoc"],
    category: "text-processing",
  },
  {
    name: "markdown",
    description: "Text-to-HTML conversion tool for web writers.",
    useCases: ["Quickly render markdown files to HTML"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["pandoc"],
    category: "text-processing",
  },
  {
    name: "envsubst",
    description: "Substitute environment variables in shell format strings.",
    useCases: ["Inject environment variables into a template configuration file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["sed", "awk"],
    category: "text-processing",
  },
];