import { CommandDef } from "./CommandDef";

export const linuxCmdsCompression: CommandDef[] = [
  {
    name: "tar",
    description: "An archiving utility.",
    useCases: ["Pack multiple files into one archive"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { 
      "-x": { description: "Extract" }, 
      "-c": { description: "Create" }, 
      "-z": { description: "Gzip filter" },
      "-v": { description: "Verbosely list files processed" },
      "-f": { description: "Use archive file (required to specify filename)" }
    },
    exampleOutputLines: [],
    relatedCommands: ["gzip", "zip"],
    category: "compression",
  },
  {
    name: "gzip",
    description: "Compress or expand files.",
    useCases: ["Shrink a text log"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-d": { description: "Decompress" } },
    exampleOutputLines: [],
    relatedCommands: ["gunzip", "tar"],
    category: "compression",
  },
  {
    name: "gunzip",
    description: "Decompress files compressed by gzip.",
    useCases: ["Extract .gz files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["gzip", "tar"],
    category: "compression",
  },
  {
    name: "zip",
    description: "Package and compress files.",
    useCases: ["Create a standard cross-platform archive"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-r": { description: "Recursively zip directories" } },
    exampleOutputLines: [],
    relatedCommands: ["unzip"],
    category: "compression",
  },
  {
    name: "unzip",
    description: "List, test and extract compressed files in a ZIP archive.",
    useCases: ["Extract standard .zip files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-d": { description: "Extract to directory" } },
    exampleOutputLines: [],
    relatedCommands: ["zip"],
    category: "compression",
  },
  {
    name: "bzip2",
    description: "A block-sorting file compressor.",
    useCases: ["Highly compress a large archive"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-d": { description: "Decompress" } },
    exampleOutputLines: [],
    relatedCommands: ["bunzip2", "tar"],
    category: "compression",
  },
  {
    name: "bunzip2",
    description: "Decompress bzip2 files.",
    useCases: ["Extract .bz2 files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["bzip2"],
    category: "compression",
  },
  {
    name: "xz",
    description: "Compress or decompress .xz and .lzma files.",
    useCases: ["Create ultra-compressed archives"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-d": { description: "Decompress" } },
    exampleOutputLines: [],
    relatedCommands: ["unxz", "tar"],
    category: "compression",
  },
  {
    name: "unxz",
    description: "Decompress xz files.",
    useCases: ["Extract .xz files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["xz"],
    category: "compression",
  },
  {
    name: "zstd",
    description: "Zstandard - Fast real-time compression algorithm.",
    useCases: ["Quickly compress backups"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-d": { description: "Decompress" } },
    exampleOutputLines: [],
    relatedCommands: ["gzip"],
    category: "compression",
  },
  {
    name: "7z",
    description: "A file archiver with highest compression ratio.",
    useCases: ["Extract .7z, .rar, or .iso files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "x": { description: "Extract with full paths" } },
    exampleOutputLines: [],
    relatedCommands: ["zip", "unzip"],
    category: "compression",
  },
  {
    name: "rar",
    description: "Archive files with compression.",
    useCases: ["Create .rar archives"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "a": { description: "Add to archive" } },
    exampleOutputLines: [],
    relatedCommands: ["unrar"],
    category: "compression",
  },
  {
    name: "unrar",
    description: "Extract, test and view RAR archives.",
    useCases: ["Extract downloaded .rar packages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "x": { description: "Extract with full path" } },
    exampleOutputLines: [],
    relatedCommands: ["rar"],
    category: "compression",
  },
  {
    name: "cpio",
    description: "Copy files to and from archives.",
    useCases: ["Extract RPM or initramfs images"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-i": { description: "Extract" }, "-d": { description: "Make directories" } },
    exampleOutputLines: [],
    relatedCommands: ["tar"],
    category: "compression",
  },
  {
    name: "ar",
    description: "Create, modify, and extract from archives (.a / .deb).",
    useCases: ["Unpack Debian .deb binaries manually"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "x": { description: "Extract files" } },
    exampleOutputLines: [],
    relatedCommands: ["tar", "dpkg"],
    category: "compression",
  },
  {
    name: "zcat",
    description: "Compress or expand files to standard output.",
    useCases: ["Read zipped log files without unzipping them"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zless", "cat"],
    category: "compression",
  },
  {
    name: "zless",
    description: "File perusal filter for crt viewing of compressed text.",
    useCases: ["Page through a .gz file securely"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zcat", "less"],
    category: "compression",
  }
];