import { CommandDef } from "./CommandDef";

export const linuxCmdsTextProcessingTerminal: CommandDef[] = [
  {
    name: "tput",
    description: "Initialize a terminal or query terminfo database.",
    useCases: ["Clear screen or change text color in a script safely"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["reset", "stty"],
    category: "text-processing",
  },
  {
    name: "dialog",
    description: "Display dialog boxes from shell scripts.",
    useCases: ["Create interactive yes/no or menu prompts in terminal scripts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--msgbox": { description: "Display a message box" },
      "--menu": { description: "Display a menu" },
    },
    exampleOutputLines: [],
    relatedCommands: ["whiptail"],
    category: "text-processing",
  },
  {
    name: "whiptail",
    description: "Display dialog boxes from shell scripts (alternative to dialog).",
    useCases: ["Create terminal-based user interfaces for setup scripts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--yesno": { description: "Display a boolean choice box" },
    },
    exampleOutputLines: [],
    relatedCommands: ["dialog"],
    category: "text-processing",
  },
  {
    name: "stty",
    description: "Change and print terminal line settings.",
    useCases: ["Hide typed passwords by disabling echo (stty -echo)"],
    isDangerous: false,
    dangerWarning: "Incorrect settings can make the terminal unusable until reset.",
    safeAlternatives: [],
    flags: {
      "-a": { description: "Print all current settings" },
    },
    exampleOutputLines: [],
    relatedCommands: ["tput", "reset"],
    category: "text-processing",
  },
  {
    name: "reset",
    description: "Terminal initialization and reset.",
    useCases: ["Fix a terminal that is printing gibberish after reading a binary file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["tput", "stty", "clear"],
    category: "text-processing",
  },
  {
    name: "tset",
    description: "Terminal initialization.",
    useCases: ["Set terminal characteristics based on terminal type"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["reset"],
    category: "text-processing",
  },
  {
    name: "hexdump",
    description: "Display file contents in hexadecimal, decimal, octal, or ASCII.",
    useCases: ["Inspect binary files byte by byte"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-C": { description: "Canonical hex+ASCII display" },
    },
    exampleOutputLines: [],
    relatedCommands: ["hd", "xxd", "od"],
    category: "text-processing",
  },
  {
    name: "hd",
    description: "Alias for hexdump -C (Canonical hex+ASCII display).",
    useCases: ["Quickly view binary data alongside its ASCII representation"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["hexdump", "xxd"],
    category: "text-processing",
  },
  {
    name: "cmp",
    description: "Compare two files byte by byte.",
    useCases: ["Verify if two binary files are identical"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-s": { description: "Silent mode, exit status only" },
    },
    exampleOutputLines: [],
    relatedCommands: ["diff", "comm"],
    category: "text-processing",
  },
  {
    name: "meld",
    description: "Visual diff and merge tool.",
    useCases: ["Compare and merge code directories graphically"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["diff", "vimdiff", "kdiff3"],
    category: "text-processing",
  },
  {
    name: "vimdiff",
    description: "Edit two, three or four versions of a file with Vim and show differences.",
    useCases: ["Resolve git merge conflicts directly in the terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["diff", "meld"],
    category: "text-processing",
  },
  {
    name: "kdiff3",
    description: "Compare and merge 2 or 3 files or directories.",
    useCases: ["Perform three-way merges visually"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["meld", "diff"],
    category: "text-processing",
  },
  {
    name: "b2sum",
    description: "Compute and check BLAKE2 message digest.",
    useCases: ["Generate high-speed, secure cryptographic hashes"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-c": { description: "Check sums against a file" },
    },
    exampleOutputLines: [],
    relatedCommands: ["sha256sum", "md5sum"],
    category: "text-processing",
  },
  {
    name: "rhash",
    description: "Utility for calculation and verification of hash sums.",
    useCases: ["Calculate multiple hash algorithms simultaneously"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-a": { description: "Calculate all supported hashes" },
    },
    exampleOutputLines: [],
    relatedCommands: ["b2sum", "sha256sum"],
    category: "text-processing",
  },
  {
    name: "sum",
    description: "Checksum and count the blocks in a file (legacy).",
    useCases: ["Compute legacy checksums on old systems"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-r": { description: "Use BSD checksum algorithm" },
      "-s": { description: "Use System V checksum algorithm" },
    },
    exampleOutputLines: [],
    relatedCommands: ["cksum", "md5sum"],
    category: "text-processing",
  },
  {
    name: "ptx",
    description: "Produce a permuted index of file contents.",
    useCases: ["Generate keyword-in-context indexes for text analysis"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-O": { description: "Output in roff format" },
    },
    exampleOutputLines: [],
    relatedCommands: ["sort", "awk"],
    category: "text-processing",
  },
  {
    name: "tsort",
    description: "Perform topological sort.",
    useCases: ["Determine dependency order from a list of directed edges"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["sort"],
    category: "text-processing",
  },
  {
    name: "luit",
    description: "Locale and ISO 2022 support for Unicode terminals.",
    useCases: ["Run an application requiring a different character encoding in a UTF-8 terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-encoding": { description: "Set the character encoding of the application" },
    },
    exampleOutputLines: [],
    relatedCommands: ["iconv"],
    category: "text-processing",
  },
  {
    name: "sponge",
    description: "Soak up standard input and write to a file.",
    useCases: ["Read from and write to the same file in a pipeline without truncating it initially"],
    isDangerous: true,
    dangerWarning: "Will completely overwrite the target file. If the previous command fails, the file will be truncated.",
    safeAlternatives: ["Write output to a temporary file and use mv on success"],
    flags: {
      "-a": { description: "Append to the file instead of overwriting" },
    },
    exampleOutputLines: [],
    relatedCommands: ["tee", "cat"],
    category: "text-processing",
  },
  {
    name: "ts",
    description: "Timestamp input.",
    useCases: ["Add timestamps to each line of a long-running process log"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-s": { description: "Print time since the start of the program" },
    },
    exampleOutputLines: [],
    relatedCommands: ["date", "awk"],
    category: "text-processing",
  },
  {
    name: "chronic",
    description: "Run command quietly unless it fails (part of moreutils).",
    useCases: ["Prevent cron jobs from sending emails unless an error occurs"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["sponge"],
    category: "text-processing",
  },
  {
    name: "ifne",
    description: "Run command if the standard input is not empty (part of moreutils).",
    useCases: ["Only trigger an email or script if preceding grep actually found results"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["xargs"],
    category: "text-processing",
  },
  {
    name: "pee",
    description: "Tee standard input to pipes (part of moreutils).",
    useCases: ["Send identical input to multiple separate commands simultaneously"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["tee"],
    category: "text-processing",
  },
  {
    name: "zrun",
    description: "Automatically uncompress arguments to command (part of moreutils).",
    useCases: ["Run a tool on gzipped files even if the tool doesn't support gzip natively"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zcat"],
    category: "text-processing",
  },
  {
    name: "combine",
    description: "Combine sets of lines from two files using boolean operations (part of moreutils).",
    useCases: ["Perform UNION, INTERSECT, or DIFFERENCE between two lists of items"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["comm", "grep"],
    category: "text-processing",
  },
  {
    name: "vidir",
    description: "Edit directory contents in a text editor (part of moreutils).",
    useCases: ["Mass rename, move, or delete files in a directory using vim or nano"],
    isDangerous: true,
    dangerWarning: "Saving the text file and exiting will immediately perform renames or deletions based on your edits.",
    safeAlternatives: ["Use a dry-run rename tool"],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["rename", "mv"],
    category: "text-processing",
  }
];