import { CommandDef } from "./CommandDef";

export const linuxCmdsNewCommands: CommandDef[] = [
  {
    name: "bash",
    description: "GNU Bourne-Again SHell.",
    useCases: ["Check current bash shell version", "Start a new bash session"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--version": { description: "Display the version of bash" },
    },
    exampleOutputLines: [],
    relatedCommands: ["zsh", "sh"],
    category: "shell",
  },
  {
    name: "zsh",
    description: "The Z shell.",
    useCases: ["Check current zsh shell version", "Start a new zsh session"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--version": { description: "Display the version of zsh" },
    },
    exampleOutputLines: [],
    relatedCommands: ["bash", "sh"],
    category: "shell",
  },
  {
    name: "printenv",
    description: "Print all or part of environment.",
    useCases: ["Print all environment variables", "Print a specific variable value"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["env", "export", "set"],
    category: "shell",
  },
  {
    name: "tldr",
    description: "Simplified community-driven man pages.",
    useCases: ["Get quick practical examples for a command", "Learn a command faster than reading man pages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["man", "cheat", "help"],
    category: "shell",
  },
  {
    name: "cheat",
    description: "Create and view interactive cheat sheets on the command line.",
    useCases: ["View a command cheat sheet", "Get quick reference for common command patterns"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-l": { description: "List all available cheat sheets" },
      "-t": { description: "Tag filter" },
    },
    exampleOutputLines: [],
    relatedCommands: ["tldr", "man"],
    category: "shell",
  },
  {
    name: "csvstat",
    description: "Print descriptive statistics for each column in a CSV file (part of csvkit).",
    useCases: ["Get statistics on CSV data like min, max, mean"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["csvcut", "csvgrep", "datamash"],
    category: "text-processing",
  },
  {
    name: "csvcut",
    description: "Filter and truncate CSV files by column (part of csvkit).",
    useCases: ["Extract specific columns from a CSV file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-c": { description: "Select specific columns by name or index" },
    },
    exampleOutputLines: [],
    relatedCommands: ["csvstat", "csvgrep", "cut"],
    category: "text-processing",
  },
  {
    name: "csvgrep",
    description: "Filter CSV rows using string and regex matches (part of csvkit).",
    useCases: ["Filter CSV rows that match a pattern"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-c": { description: "Column to search" },
      "-m": { description: "String to match" },
      "-r": { description: "Regex pattern to match" },
    },
    exampleOutputLines: [],
    relatedCommands: ["csvstat", "csvcut", "grep"],
    category: "text-processing",
  },
  {
    name: "nano",
    description: "GNU nano, a simple text editor.",
    useCases: ["Edit text files with a beginner-friendly interface", "Quick edits to configuration files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-B": { description: "Back up the file before editing" },
      "-l": { description: "Show line numbers" },
      "-m": { description: "Enable mouse support" }
    },
    exampleOutputLines: [],
    relatedCommands: ["vim", "vi", "micro"],
    category: "shell",
  },
  {
    name: "vimtutor",
    description: "A built-in interactive tutorial for learning Vim.",
    useCases: ["Learn Vim basics interactively", "Practice Vim motions and commands"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["vim", "vi"],
    category: "shell",
  },
  {
    name: "gedit",
    description: "GNOME text editor.",
    useCases: ["Edit text files with a graphical interface"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--new-window": { description: "Open a new top-level window" }
    },
    exampleOutputLines: [],
    relatedCommands: ["nano", "kate"],
    category: "shell",
  },
  {
    name: "micro",
    description: "A modern and intuitive terminal-based text editor.",
    useCases: ["Edit files in the terminal with familiar keyboard shortcuts (Ctrl+S, Ctrl+C)", "Beginner-friendly alternative to vim and nano"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["nano", "vim"],
    category: "shell",
  },
  {
    name: "code",
    description: "Visual Studio Code editor.",
    useCases: ["Open files or directories in VS Code from the terminal", "Launch VS Code with a specific workspace"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      ".": { description: "Open the current directory in VS Code" },
      "-d": { description: "Compare two files (diff mode)" },
      "-r": { description: "Reuse the most recently active window" },
      "-g": { description: "Open a file at specific line and character" }
    },
    exampleOutputLines: [],
    relatedCommands: ["vim", "nano", "subl"],
    category: "shell",
  },
  {
    name: "namei",
    description: "Trace a pathname to its endpoint, showing permissions at each level",
    useCases: ["Diagnose permission issues along a file path", "Check directory permissions at every level", "Debug 'Permission denied' errors by finding which directory blocks access"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-l": { description: "Show permissions, owner, and group at each path component" },
      "-m": { description: "Show modes in octal" },
      "-x": { description: "Show mount point crossings" }
    },
    exampleOutputLines: [],
    relatedCommands: ["stat", "ls", "chmod"],
    category: "file-management"
  },
  {
    name: "finger",
    description: "Display information about system users including login time, idle time, and plan",
    useCases: ["Look up user information", "Check who is logged in and their activity", "View user's full name and shell"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-l": { description: "Long format (default)" },
      "-s": { description: "Short format" },
      "-p": { description: "Omit .plan and .project files" }
    },
    exampleOutputLines: [],
    relatedCommands: ["who", "w", "id", "last"],
    category: "admin-security"
  },
  {
    name: "ac",
    description: "Display statistics about user login time from wtmp records",
    useCases: ["Track total login hours per user", "Audit system usage by day", "Generate user activity reports"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Show daily breakdown" },
      "-p": { description: "Show per-user totals" },
      "-y": { description: "Include year in date display" }
    },
    exampleOutputLines: [],
    relatedCommands: ["last", "who", "w"],
    category: "admin-security"
  },
  {
    name: "faillock",
    description: "Display and manage failed authentication attempts for user accounts",
    useCases: ["Check failed login attempts for a user", "Reset failed attempt counter after lockout", "Audit security events"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--user": { description: "Specify the user to query or reset" },
      "--reset": { description: "Reset the failed authentication counter" },
      "--dir": { description: "Use a non-default tally directory" }
    },
    exampleOutputLines: [],
    relatedCommands: ["passwd", "pam_faillock", "last"],
    category: "admin-security"
  }
];