import { CommandDef } from "./CommandDef";

export const linuxCmdsTextProcessingData: CommandDef[] = [
  {
    name: "numfmt",
    description: "Convert numbers from/to human-readable strings.",
    useCases: ["Convert raw bytes into human-readable sizes (like 1.5G)"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--to": { description: "Format output according to standard (e.g., iec)" },
    },
    exampleOutputLines: [],
    relatedCommands: ["awk"],
    category: "text-processing",
  },
  {
    name: "shuf",
    description: "Generate random permutations.",
    useCases: ["Shuffle lines in a file", "Pick a random line from a list"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-n": { description: "Output at most this many lines" },
      "-e": { description: "Treat arguments as input lines" },
    },
    exampleOutputLines: [],
    relatedCommands: ["sort"],
    category: "text-processing",
  },
  {
    name: "chardet",
    description: "Universal character encoding detector.",
    useCases: ["Detect the encoding of a mystery text file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["uchardet", "iconv"],
    category: "text-processing",
  },
  {
    name: "uchardet",
    description: "Encoding detector library.",
    useCases: ["Guess the character encoding of a file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["chardet"],
    category: "text-processing",
  },
  {
    name: "nkf",
    description: "Network Kanji Filter.",
    useCases: ["Convert encodings of Japanese text files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-w": { description: "Output in UTF-8 encoding" },
    },
    exampleOutputLines: [],
    relatedCommands: ["iconv"],
    category: "text-processing",
  },
  {
    name: "idn",
    description: "Internationalized Domain Names command line tool.",
    useCases: ["Convert non-ASCII domain names to Punycode"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-a": { description: "Convert to ACE (ASCII Compatible Encoding)" },
    },
    exampleOutputLines: [],
    relatedCommands: ["idn2"],
    category: "text-processing",
  },
  {
    name: "idn2",
    description: "Internationalized Domain Name (IDNA2008) tool.",
    useCases: ["Encode and decode IDN domains compliant with IDNA2008"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["idn"],
    category: "text-processing",
  },
  {
    name: "gawk",
    description: "GNU awk, a pattern scanning and processing language.",
    useCases: ["Advanced text parsing and reporting"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-v": { description: "Assign a variable before execution" },
    },
    exampleOutputLines: [],
    relatedCommands: ["awk", "sed"],
    category: "text-processing",
  },
  {
    name: "perl",
    description: "The Perl 5 language interpreter (used for text processing).",
    useCases: ["Perform complex regular expression replacements inline"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-p": { description: "Assume loop like awk, print line also" },
      "-i": { description: "Edit files in-place" },
      "-e": { description: "Execute one line of program" },
    },
    exampleOutputLines: [],
    relatedCommands: ["sed", "awk"],
    category: "text-processing",
  },
  {
    name: "m4",
    description: "Macro processor.",
    useCases: ["Expand macros in source code or config files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-D": { description: "Define a macro at the command line" },
    },
    exampleOutputLines: [],
    relatedCommands: ["cpp", "envsubst"],
    category: "text-processing",
  },
  {
    name: "cpp",
    description: "The C Preprocessor.",
    useCases: ["Process #include and #define directives in text files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-E": { description: "Stop after the preprocessing stage" },
    },
    exampleOutputLines: [],
    relatedCommands: ["m4"],
    category: "text-processing",
  },
  {
    name: "datamash",
    description: "Command-line statistical operations.",
    useCases: ["Calculate sum, mean, or standard deviation of columns in a text file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-g": { description: "Group by a specific field" },
    },
    exampleOutputLines: [],
    relatedCommands: ["awk", "mlr"],
    category: "text-processing",
  },
  {
    name: "mlr",
    description: "Miller is like awk, sed, cut, join, and sort for name-indexed data.",
    useCases: ["Process CSV, JSON, and tabular data intuitively"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "--csv": { description: "Use CSV format for input and output" },
      "--ijson": { description: "Use JSON format for input" },
    },
    exampleOutputLines: [],
    relatedCommands: ["jq", "awk", "datamash"],
    category: "text-processing",
  },
  {
    name: "csvtool",
    description: "Handy command line tool for handling CSV files.",
    useCases: ["Extract specific columns from a CSV file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "col": { description: "Extract specific columns" },
    },
    exampleOutputLines: [],
    relatedCommands: ["mlr", "xsv"],
    category: "text-processing",
  },
  {
    name: "sq",
    description: "Command line data wrangling tool (jq for databases).",
    useCases: ["Query JSON, CSV or Excel files with SQL"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["jq", "mlr"],
    category: "text-processing",
  },
  {
    name: "xsv",
    description: "A fast CSV command line toolkit written in Rust.",
    useCases: ["Index, slice, and analyze massive CSV files instantly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "select": { description: "Select columns by index or name" },
      "search": { description: "Filter rows by a regex" },
    },
    exampleOutputLines: [],
    relatedCommands: ["mlr", "csvtool"],
    category: "text-processing",
  },
  {
    name: "tsv-utils",
    description: "Command line utilities for tabular data files.",
    useCases: ["Filter, sort, and process TSV files efficiently"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["xsv", "mlr"],
    category: "text-processing",
  },
];