import { CommandDef } from "./CommandDef";

export const linuxCmdsShell: CommandDef[] = [
  {
    name: "alias",
    description: "Define or display aliases.",
    useCases: ["Create shortcut commands"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["unalias"],
    category: "shell",
  },
  {
    name: "unalias",
    description: "Remove alias definitions.",
    useCases: ["Delete a custom shortcut temporarily"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-a": { description: "Remove all aliases" } },
    exampleOutputLines: [],
    relatedCommands: ["alias"],
    category: "shell",
  },
  {
    name: "export",
    description: "Set an environment variable.",
    useCases: ["Make variables available to child processes"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["env"],
    category: "shell",
  },
  {
    name: "source",
    description: "Read and execute commands from a file.",
    useCases: ["Reload .bashrc settings"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["."],
    category: "shell",
  },
  {
    name: "history",
    description: "Display or manipulate the history list.",
    useCases: ["Find previously run commands"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { 
      "-c": { description: "Clear history" },
      "-d": { description: "Delete the history entry at specified position" }
    },
    exampleOutputLines: [],
    relatedCommands: ["!"],
    category: "shell",
  },
  {
    name: "man",
    description: "Interface to the system reference manuals.",
    useCases: ["Read detailed documentation"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-k": { description: "Search the short descriptions and manual page names (equivalent to apropos)" },
      "-f": { description: "Display a short description (equivalent to whatis)" }
    },
    exampleOutputLines: [],
    relatedCommands: ["info", "help"],
    category: "shell",
  },
  {
    name: "info",
    description: "Read Info documents.",
    useCases: ["Read deeply nested GNU documentation"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["man"],
    category: "shell",
  },
  {
    name: "help",
    description: "Display information about builtin commands.",
    useCases: ["Learn about shell builtins like cd or read"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["man"],
    category: "shell",
  },
  {
    name: "which",
    description: "Locate a command.",
    useCases: ["Find path to executable"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-a": { description: "Print all matching executables in PATH, not just the first" }
    },
    exampleOutputLines: [],
    relatedCommands: ["whereis", "type"],
    category: "shell",
  },
  {
    name: "whereis",
    description: "Locate the binary, source, and manual page files.",
    useCases: ["Find all paths related to a command"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-b": { description: "Search only for binaries" },
      "-m": { description: "Search only for manual pages" },
      "-s": { description: "Search only for source files" }
    },
    exampleOutputLines: [],
    relatedCommands: ["which"],
    category: "shell",
  },
  {
    name: "type",
    description: "Display information about command type.",
    useCases: ["Check if command is an alias or builtin"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-a": { description: "Show all locations containing an executable named 'name'" },
      "-t": { description: "Show only the type of the command (alias, builtin, file, function, keyword)" }
    },
    exampleOutputLines: [],
    relatedCommands: ["which"],
    category: "shell",
  },
  {
    name: "env",
    description: "Run a program in a modified environment.",
    useCases: ["List all environment variables"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["export", "set"],
    category: "shell",
  },
  {
    name: "set",
    description: "Set or unset shell options.",
    useCases: ["Enable shell script strict mode (set -e)"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["env"],
    category: "shell",
  },
  {
    name: "clear",
    description: "Clear the terminal screen.",
    useCases: ["Clean up terminal output"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["reset"],
    category: "shell",
  },
  {
    name: "exit",
    description: "Exit the shell.",
    useCases: ["Close a terminal or SSH session"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["logout"],
    category: "shell",
  },
  {
    name: "logout",
    description: "Exit a login shell.",
    useCases: ["Log out of a session"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["exit"],
    category: "shell",
  },
  {
    name: "test",
    description: "Check file types and compare values.",
    useCases: ["Evaluate conditions in scripts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["["],
    category: "shell",
  },
  {
    name: "eval",
    description: "Evaluate several commands/arguments.",
    useCases: ["Execute dynamically generated code strings"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["exec"],
    category: "shell",
  },
  {
    name: "exec",
    description: "Replace the shell with the given command.",
    useCases: ["Run a command, effectively ending the current script"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["eval"],
    category: "shell",
  },
  {
    name: "trap",
    description: "Trap signals and other information.",
    useCases: ["Clean up temp files if a script is killed via Ctrl+C"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["kill"],
    category: "shell",
  },
  {
    name: "wait",
    description: "Await process completion.",
    useCases: ["Pause script until background jobs finish"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["jobs"],
    category: "shell",
  },
  {
    name: "read",
    description: "Read a line from standard input.",
    useCases: ["Prompt for user input in bash scripts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-p": { description: "Prompt string" } },
    exampleOutputLines: [],
    relatedCommands: ["echo"],
    category: "shell",
  },
  {
    name: "shift",
    description: "Shift positional parameters.",
    useCases: ["Iterate through script arguments"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["getopts"],
    category: "shell",
  },
  {
    name: "getopts",
    description: "Parse utility options.",
    useCases: ["Parse flags (like -a -b) passed to a shell script"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["shift"],
    category: "shell",
  },
  {
    name: "declare",
    description: "Set variable values and attributes.",
    useCases: ["Create integer variables or arrays in bash"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-a": { description: "Make indexed array" } },
    exampleOutputLines: [],
    relatedCommands: ["local"],
    category: "shell",
  },
  {
    name: "local",
    description: "Define a local variable inside a function.",
    useCases: ["Prevent function variables from leaking to global scope"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["declare"],
    category: "shell",
  },
  {
    name: "return",
    description: "Return from a shell function.",
    useCases: ["Pass an exit status out of a function"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["exit"],
    category: "shell",
  },
  {
    name: "break",
    description: "Exit from a for, while, or until loop.",
    useCases: ["Stop a loop early based on a condition"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["continue"],
    category: "shell",
  },
  {
    name: "continue",
    description: "Resume the next iteration of a loop.",
    useCases: ["Skip current loop iteration and move to next"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["break"],
    category: "shell",
  },
  {
    name: "sleep",
    description: "Delay for a specified amount of time.",
    useCases: ["Pause execution of a script"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["wait"],
    category: "shell",
  },
  {
    name: "yes",
    description: "Output a string repeatedly until killed.",
    useCases: ["Automatically answer 'y' to prompts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["echo"],
    category: "shell",
  },
  {
    name: "true",
    description: "Do nothing, successfully.",
    useCases: ["Create an infinite loop (while true)"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["false"],
    category: "shell",
  },
  {
    name: "false",
    description: "Do nothing, unsuccessfully.",
    useCases: ["Force a failure condition"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["true"],
    category: "shell",
  },
  {
    name: "seq",
    description: "Print a sequence of numbers.",
    useCases: ["Generate loops dynamically (for i in $(seq 1 10))"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["echo"],
    category: "shell",
  },
  {
    name: "factor",
    description: "Print prime factors.",
    useCases: ["Mathematical factorization in scripts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["bc"],
    category: "shell",
  },
  {
    name: "bc",
    description: "An arbitrary precision calculator language.",
    useCases: ["Do floating-point math in bash"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-l": { description: "Use standard math library" } },
    exampleOutputLines: [],
    relatedCommands: ["expr"],
    category: "shell",
  },
  {
    name: "expr",
    description: "Evaluate expressions.",
    useCases: ["Basic integer math"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["bc"],
    category: "shell",
  },
  {
    name: "git",
    description: "The stupid content tracker (version control).",
    useCases: ["Clone, commit, and push source code"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "commit": { description: "Record changes" }, "push": { description: "Update remote refs" } },
    exampleOutputLines: [],
    relatedCommands: ["svn"],
    category: "shell",
  },
  {
    name: "screen",
    description: "Screen manager with VT100/ANSI terminal emulation.",
    useCases: ["Keep processes running after SSH disconnect"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-r": { description: "Resume detached session" } },
    exampleOutputLines: [],
    relatedCommands: ["tmux", "nohup"],
    category: "shell",
  },
  {
    name: "tmux",
    description: "Terminal multiplexer.",
    useCases: ["Split terminals, keep sessions persistent"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "attach": { description: "Attach to session" } },
    exampleOutputLines: [],
    relatedCommands: ["screen"],
    category: "shell",
  },
  {
    name: "cron",
    description: "Daemon to execute scheduled commands.",
    useCases: ["Run daily backup scripts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["anacron", "crontab"],
    category: "shell",
  },
  {
    name: "anacron",
    description: "Runs commands periodically, no assumption of 24/7 uptime.",
    useCases: ["Schedule tasks on laptops that sleep"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["cron"],
    category: "shell",
  },
  {
    name: ":(){ :|:& };:",
    description: "A shell fork bomb.",
    useCases: ["Crash a system (malicious)"],
    isDangerous: true,
    dangerWarning: "This is a fork bomb. It will recursively spawn processes until the system crashes.",
    safeAlternatives: ["Never run this command."],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: [],
    category: "shell",
  },
  {
    name: "shutdown",
    description: "Halt, power-off or reboot the machine.",
    useCases: ["Safely turn off the system"],
    isDangerous: true,
    dangerWarning: "Will instantly take remote servers offline, effectively locking out access until manual boot.",
    safeAlternatives: ["Use 'shutdown +10' to give notice"],
    flags: { "-r": { description: "Reboot" } },
    exampleOutputLines: [],
    relatedCommands: ["reboot", "poweroff", "halt"],
    category: "shell",
  },
  {
    name: "reboot",
    description: "Reboot the system.",
    useCases: ["Restart after a kernel update"],
    isDangerous: true,
    dangerWarning: "Ends all user sessions and services immediately.",
    safeAlternatives: ["shutdown -r +5"],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["shutdown"],
    category: "shell",
  },
  {
    name: "halt",
    description: "Halt the system.",
    useCases: ["Stop all CPU functions safely"],
    isDangerous: true,
    dangerWarning: "Pulls down the OS without fully cutting power on some hardware.",
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["poweroff"],
    category: "shell",
  },
  {
    name: "poweroff",
    description: "Power off the system.",
    useCases: ["Send ACPI shutdown to power off"],
    isDangerous: true,
    dangerWarning: "Shuts down the server abruptly.",
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["halt"],
    category: "shell",
  },
  {
    name: "vi",
    description: "Text editor (the original visual editor).",
    useCases: ["Edit text files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-R": { description: "Read-only" }, "-r": { description: "Recover" }, "+n": { description: "Start at line n" } },
    exampleOutputLines: [],
    relatedCommands: ["vim", "nano"],
    category: "shell",
  },
  {
    name: "vim",
    description: "Vi IMproved text editor.",
    useCases: ["Edit text files", "Write code"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-R": { description: "Read-only" }, "-r": { description: "Recover" }, "+n": { description: "Start at line n" }, "-d": { description: "Diff mode" }, "-p": { description: "Open files in tabs" }, "-u": { description: "Use specific vimrc file (use NONE for no config)" } },
    exampleOutputLines: [],
    relatedCommands: ["vi", "nano", "emacs"],
    category: "shell",
  },
  {
    name: "emacs",
    description: "Extensible text editor.",
    useCases: ["Edit text files", "Write code"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-nw": { description: "No window/terminal mode" }, "--no-init-file": { description: "No init file" }, "-q": { description: "No init file" } },
    exampleOutputLines: [],
    relatedCommands: ["vi", "vim", "nano"],
    category: "shell",
  },
  {
    name: "lp",
    description: "Send files to a printer.",
    useCases: ["Send files to a printer"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-d": { description: "Destination printer" }, "-n": { description: "Number of copies" }, "-P": { description: "Page range" } },
    exampleOutputLines: [],
    relatedCommands: ["lpr", "cups"],
    category: "shell",
  },
  {
    name: "lpr",
    description: "Print files (BSD style).",
    useCases: ["Print files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-P": { description: "Printer name" }, "-#": { description: "Number of copies" }, "-h": { description: "Suppress banner page" } },
    exampleOutputLines: [],
    relatedCommands: ["lp", "cups"],
    category: "shell",
  },
  {
    name: "make",
    description: "Build automation tool.",
    useCases: ["Compile software", "Automate tasks"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-j": { description: "Parallel jobs" }, "-f": { description: "Makefile name" }, "-n": { description: "Dry run" }, "-B": { description: "Unconditionally make all targets" }, "-C": { description: "Change to directory" } },
    exampleOutputLines: [],
    relatedCommands: ["cmake", "gcc"],
    category: "shell",
  },
  {
    name: "gcc",
    description: "GNU C Compiler.",
    useCases: ["Compile C/C++ code"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-o": { description: "Output file" }, "-c": { description: "Compile only" }, "-g": { description: "Debug info" }, "-O": { description: "Optimize" }, "-O2": { description: "Optimize level 2" }, "-Wall": { description: "All warnings" }, "-I": { description: "Include path" }, "-L": { description: "Library path" }, "-l": { description: "Link library" }, "-std": { description: "C standard" } },
    exampleOutputLines: [],
    relatedCommands: ["make", "clang"],
    category: "shell",
  }
];