import { CommandDef } from "./CommandDef";

export const linuxCmdsAdminSecurity: CommandDef[] = [
  {
    name: "chmod",
    description: "Change file mode bits (permissions).",
    useCases: ["Make scripts executable", "Secure sensitive files"],
    isDangerous: true,
    dangerWarning: "Using chmod 777 or recursive chmod on critical directories can completely break system security.",
    safeAlternatives: ["Use explicit numerical modes like 644 or 755"],
    flags: { "-R": { description: "Change files and directories recursively" } },
    exampleOutputLines: [],
    relatedCommands: ["chown", "chgrp"],
    category: "admin-security",
  },
  {
    name: "chown",
    description: "Change file owner and group.",
    useCases: ["Transfer ownership of files"],
    isDangerous: true,
    dangerWarning: "Using recursive chown on root directories (/) will destroy system stability.",
    safeAlternatives: ["Verify paths carefully before pressing enter"],
    flags: { "-R": { description: "Operate recursively" } },
    exampleOutputLines: [],
    relatedCommands: ["chmod", "chgrp"],
    category: "admin-security",
  },
  {
    name: "chgrp",
    description: "Change group ownership.",
    useCases: ["Allow members of a group access to shared files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-R": { description: "Operate recursively" } },
    exampleOutputLines: [],
    relatedCommands: ["chown", "chmod"],
    category: "admin-security",
  },
  {
    name: "umask",
    description: "Set file mode creation mask.",
    useCases: ["Define default permissions for newly created files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-S": { description: "Print mask symbolically" } },
    exampleOutputLines: [],
    relatedCommands: ["chmod"],
    category: "admin-security",
  },
  {
    name: "sudo",
    description: "Execute a command as another user.",
    useCases: ["Run system commands as root"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-i": { description: "Login as target user" }, "-u": { description: "Run the command as a user other than root" } },
    exampleOutputLines: [],
    relatedCommands: ["su", "visudo"],
    category: "admin-security",
  },
  {
    name: "su",
    description: "Run a command with substitute user and group ID.",
    useCases: ["Switch fully to root or another user"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-": { description: "Start a login shell" } },
    exampleOutputLines: [],
    relatedCommands: ["sudo"],
    category: "admin-security",
  },
  {
    name: "useradd",
    description: "Create a new user or update default new user information.",
    useCases: ["Add a new account to the system"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-m": { description: "Create home directory" } },
    exampleOutputLines: [],
    relatedCommands: ["adduser", "usermod", "userdel"],
    category: "admin-security",
  },
  {
    name: "userdel",
    description: "Delete a user account and related files.",
    useCases: ["Remove access for obsolete accounts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-r": { description: "Remove home directory" } },
    exampleOutputLines: [],
    relatedCommands: ["deluser", "useradd"],
    category: "admin-security",
  },
  {
    name: "usermod",
    description: "Modify a user account.",
    useCases: ["Add a user to a supplementary group (like sudo or docker)"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-aG": { description: "Append user to group" } },
    exampleOutputLines: [],
    relatedCommands: ["useradd", "groups"],
    category: "admin-security",
  },
  {
    name: "passwd",
    description: "Change user password.",
    useCases: ["Reset user passwords"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-l": { description: "Lock account" } },
    exampleOutputLines: [],
    relatedCommands: ["chpasswd", "chage"],
    category: "admin-security",
  },
  {
    name: "groups",
    description: "Print the groups a user is in.",
    useCases: ["Check user privileges"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["id", "getent"],
    category: "admin-security",
  },
  {
    name: "who",
    description: "Show who is logged on.",
    useCases: ["See active terminal sessions"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["w", "last"],
    category: "admin-security",
  },
  {
    name: "w",
    description: "Show who is logged on and what they are doing.",
    useCases: ["Check user load and current processes"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["who", "last"],
    category: "admin-security",
  },
  {
    name: "last",
    description: "Show a listing of last logged in users.",
    useCases: ["Audit logins and system reboots"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["lastlog", "who"],
    category: "admin-security",
  },
  {
    name: "chage",
    description: "Change user password expiry information.",
    useCases: ["Force users to change passwords periodically"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-l": { description: "List account aging info" } },
    exampleOutputLines: [],
    relatedCommands: ["passwd"],
    category: "admin-security",
  },
  {
    name: "visudo",
    description: "Edit the sudoers file safely.",
    useCases: ["Grant fine-grained sudo access without breaking the syntax"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["sudo"],
    category: "admin-security",
  },
  {
    name: "adduser",
    description: "Add a user to the system (friendlier frontend for useradd).",
    useCases: ["Quickly create an account interactively"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["useradd"],
    category: "admin-security",
  },
  {
    name: "deluser",
    description: "Remove a user or group from the system.",
    useCases: ["Interactively remove accounts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["userdel"],
    category: "admin-security",
  },
  {
    name: "addgroup",
    description: "Add a group to the system.",
    useCases: ["Create a new shared access group"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["groupadd"],
    category: "admin-security",
  },
  {
    name: "delgroup",
    description: "Remove a group from the system.",
    useCases: ["Clean up unused groups"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["groupdel"],
    category: "admin-security",
  },
  {
    name: "gpasswd",
    description: "Administer /etc/group and /etc/gshadow.",
    useCases: ["Manage group administrators or set group passwords"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-a": { description: "Add user" }, "-d": { description: "Delete user" } },
    exampleOutputLines: [],
    relatedCommands: ["groups", "usermod"],
    category: "admin-security",
  },
  {
    name: "newgrp",
    description: "Log in to a new group.",
    useCases: ["Switch primary group during a session"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["groups"],
    category: "admin-security",
  },
  {
    name: "getent",
    description: "Get entries from Name Service Switch libraries.",
    useCases: ["Check if a user or group exists across local and network accounts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["id"],
    category: "admin-security",
  },
  {
    name: "apt",
    description: "High-level package management utility (Debian/Ubuntu).",
    useCases: ["Install, update, remove packages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "update": { description: "Update sources" }, "install": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["apt-get", "dpkg"],
    category: "package-management",
  },
  {
    name: "apt-get",
    description: "APT package handling utility.",
    useCases: ["Robust package management for scripts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["apt"],
    category: "package-management",
  },
  {
    name: "apt-cache",
    description: "Query the APT cache.",
    useCases: ["Search for packages without installing"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "search": { description: "Search by keyword" } },
    exampleOutputLines: [],
    relatedCommands: ["apt"],
    category: "package-management",
  },
  {
    name: "dpkg",
    description: "Package manager for Debian.",
    useCases: ["Install local .deb files directly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-i": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["apt"],
    category: "package-management",
  },
  {
    name: "yum",
    description: "Package manager for older RHEL/CentOS systems.",
    useCases: ["Manage RPM packages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["dnf", "rpm"],
    category: "package-management",
  },
  {
    name: "dnf",
    description: "Next-generation package manager for Fedora/RHEL/CentOS.",
    useCases: ["Install modern RPM packages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["yum", "rpm"],
    category: "package-management",
  },
  {
    name: "rpm",
    description: "RPM Package Manager.",
    useCases: ["Install local .rpm files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-i": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["dnf", "yum"],
    category: "package-management",
  },
  {
    name: "pacman",
    description: "Package manager for Arch Linux.",
    useCases: ["Install rolling release packages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-S": { description: "Sync package" } },
    exampleOutputLines: [],
    relatedCommands: ["yay"],
    category: "package-management",
  },
  {
    name: "snap",
    description: "Tool to interact with snaps.",
    useCases: ["Install containerized software"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["flatpak"],
    category: "package-management",
  },
  {
    name: "flatpak",
    description: "Build and install flatpak applications and runtimes.",
    useCases: ["Install sandboxed desktop apps"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["snap"],
    category: "package-management",
  },
  {
    name: "pip",
    description: "Package installer for Python.",
    useCases: ["Install Python libraries"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["pip3", "npm"],
    category: "package-management",
  },
  {
    name: "pip3",
    description: "Package installer for Python 3.",
    useCases: ["Install Python 3 specific libraries"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["pip"],
    category: "package-management",
  },
  {
    name: "gem",
    description: "Ruby package manager.",
    useCases: ["Install Ruby libraries"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install gem" } },
    exampleOutputLines: [],
    relatedCommands: ["npm", "pip"],
    category: "package-management",
  },
  {
    name: "npm",
    description: "Node package manager.",
    useCases: ["Install JavaScript libraries"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install module" } },
    exampleOutputLines: [],
    relatedCommands: ["yarn", "pip"],
    category: "package-management",
  },
  {
    name: "cargo",
    description: "Rust package manager and build tool.",
    useCases: ["Compile Rust applications"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "build": { description: "Compile package" } },
    exampleOutputLines: [],
    relatedCommands: ["npm"],
    category: "package-management",
  },
  {
    name: "brew",
    description: "Homebrew package manager.",
    useCases: ["Install macOS/Linux secondary tools"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "install": { description: "Install formula" } },
    exampleOutputLines: [],
    relatedCommands: ["apt"],
    category: "package-management",
  },
  {
    name: "zypper",
    description: "Command-line interface to ZYpp system management (openSUSE).",
    useCases: ["Manage packages on SUSE"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "in": { description: "Install package" } },
    exampleOutputLines: [],
    relatedCommands: ["apt", "dnf"],
    category: "package-management",
  },
  {
    name: "apk",
    description: "Alpine Linux package manager.",
    useCases: ["Install packages inside lightweight Docker containers"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "add": { description: "Add package" } },
    exampleOutputLines: [],
    relatedCommands: ["apt"],
    category: "package-management",
  },
  {
    name: "chroot",
    description: "Run command or interactive shell with special root directory.",
    useCases: ["Repair a broken OS from a live CD"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["mount"],
    category: "admin-security",
  },
  {
    name: "capabilities",
    description: "Overview of Linux capabilities (man 7 capabilities).",
    useCases: ["Provide specific privileges to binaries without full root"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["setcap", "getcap"],
    category: "admin-security",
  },
  {
    name: "setfacl",
    description: "Set file access control lists.",
    useCases: ["Grant granular permissions beyond standard user/group"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-m": { description: "Modify ACL" } },
    exampleOutputLines: [],
    relatedCommands: ["getfacl", "chmod"],
    category: "admin-security",
  },
  {
    name: "getfacl",
    description: "Get file access control lists.",
    useCases: ["View extended permissions of a file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["setfacl"],
    category: "admin-security",
  },
  {
    name: "sestatus",
    description: "SELinux status tool.",
    useCases: ["Check if SELinux is enforcing or permissive"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["setenforce"],
    category: "admin-security",
  },
  {
    name: "setenforce",
    description: "Modify the mode SELinux is running in.",
    useCases: ["Temporarily disable SELinux to troubleshoot permissions"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["sestatus"],
    category: "admin-security",
  },
  {
    name: "apparmor_status",
    description: "Check the current status of AppArmor.",
    useCases: ["Verify which profiles are loaded and enforcing"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["sestatus"],
    category: "admin-security",
  },
  {
    name: "fail2ban-client",
    description: "Configure and control the fail2ban server.",
    useCases: ["Check blocked IP addresses", "Unban a mistaken IP"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "status": { description: "Show jails" } },
    exampleOutputLines: [],
    relatedCommands: ["iptables"],
    category: "admin-security",
  },
  {
    name: "auditctl",
    description: "A utility to assist controlling the kernel's audit system.",
    useCases: ["Monitor specific files for unauthorized changes"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-w": { description: "Watch a path" } },
    exampleOutputLines: [],
    relatedCommands: ["ausearch"],
    category: "admin-security",
  },
  {
    name: "lastlog",
    description: "Reports the most recent login of all users or of a given user.",
    useCases: ["Find dormant accounts that haven't logged in recently"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-u": { description: "Specify user" } },
    exampleOutputLines: [],
    relatedCommands: ["last", "who"],
    category: "admin-security",
  },
  {
    name: "chpasswd",
    description: "Update passwords in batch mode.",
    useCases: ["Automate password resets for multiple users"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["passwd"],
    category: "admin-security",
  },
  {
    name: "pwck",
    description: "Verify integrity of password files.",
    useCases: ["Check /etc/passwd for formatting errors or missing directories"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["grpck"],
    category: "admin-security",
  },
  {
    name: "grpck",
    description: "Verify integrity of group files.",
    useCases: ["Check /etc/group for corruption"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["pwck"],
    category: "admin-security",
  },
  {
    name: "vipw",
    description: "Safely edit the password file.",
    useCases: ["Manually edit /etc/passwd while applying file locks"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["vigr", "visudo"],
    category: "admin-security",
  },
  {
    name: "vigr",
    description: "Safely edit the group file.",
    useCases: ["Manually edit /etc/group safely"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["vipw"],
    category: "admin-security",
  },
  {
    name: "groupadd",
    description: "Create a new group.",
    useCases: ["Create a new group"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-g": { description: "Specify GID" }, "-r": { description: "Create system group" }, "-f": { description: "Force, exit success if group exists" } },
    exampleOutputLines: [],
    relatedCommands: ["addgroup", "groupdel"],
    category: "admin-security",
  },
  {
    name: "groupdel",
    description: "Delete a group.",
    useCases: ["Delete a group"],
    isDangerous: true,
    dangerWarning: "Deleting a group may cause users to lose group membership and access to shared files.",
    safeAlternatives: [],
    flags: { "-f": { description: "Force delete even if primary group" } },
    exampleOutputLines: [],
    relatedCommands: ["delgroup", "groupadd"],
    category: "admin-security",
  }
];