import { CommandDef } from "./CommandDef";

export const linuxCmdsCompressionExtra: CommandDef[] = [
  {
    name: "pigz",
    description: "Parallel Implementation of GZIP.",
    useCases: ["Compress large files much faster utilizing all CPU cores"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
      "-p": { description: "Specify the number of threads to use" },
    },
    exampleOutputLines: [],
    relatedCommands: ["gzip", "pbzip2"],
    category: "compression",
  },
  {
    name: "pbzip2",
    description: "Parallel implementation of bzip2.",
    useCases: ["Compress files with high ratio using all CPU cores"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
      "-p": { description: "Set the number of processors to use" },
    },
    exampleOutputLines: [],
    relatedCommands: ["bzip2", "pigz"],
    category: "compression",
  },
  {
    name: "pxz",
    description: "Parallel LZMA compressor using xz.",
    useCases: ["Multi-core compression for massive files requiring best compression"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
    },
    exampleOutputLines: [],
    relatedCommands: ["xz", "pixz"],
    category: "compression",
  },
  {
    name: "pixz",
    description: "Parallel, indexed xz compressor.",
    useCases: ["Compress tarballs and index them for fast random access later"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
      "-l": { description: "List contents of a pixz-compressed tarball" },
    },
    exampleOutputLines: [],
    relatedCommands: ["xz", "pxz"],
    category: "compression",
  },
  {
    name: "plzip",
    description: "Parallel lzip compressor.",
    useCases: ["Compress files efficiently using the LZMA algorithm across cores"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
    },
    exampleOutputLines: [],
    relatedCommands: ["lzip"],
    category: "compression",
  },
  {
    name: "lz4",
    description: "Extremely fast compression algorithm.",
    useCases: ["Compress system logs instantly with minimal CPU overhead"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
      "-9": { description: "High compression level" },
    },
    exampleOutputLines: [],
    relatedCommands: ["lzop", "zstd"],
    category: "compression",
  },
  {
    name: "lzop",
    description: "Compress or expand files rapidly (LZO algorithm).",
    useCases: ["Fastest possible compression for backups to disk"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
      "-U": { description: "Delete input files after successful compression" },
    },
    exampleOutputLines: [],
    relatedCommands: ["lz4"],
    category: "compression",
  },
  {
    name: "compress",
    description: "Compress data (legacy LZW algorithm).",
    useCases: ["Extract ancient .Z files on UNIX systems"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
    },
    exampleOutputLines: [],
    relatedCommands: ["uncompress", "gzip"],
    category: "compression",
  },
  {
    name: "uncompress",
    description: "Expand compressed data (legacy LZW).",
    useCases: ["Decompress legacy .Z archives"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-c": { description: "Write output on standard output" },
    },
    exampleOutputLines: [],
    relatedCommands: ["compress", "gunzip"],
    category: "compression",
  },
  {
    name: "lzip",
    description: "A lossless data compressor based on the LZMA algorithm.",
    useCases: ["Achieve high compression ratios for archiving source code"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
    },
    exampleOutputLines: [],
    relatedCommands: ["lunzip", "xz"],
    category: "compression",
  },
  {
    name: "lunzip",
    description: "Decompressor for lzip files.",
    useCases: ["Extract .lz archives"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["lzip"],
    category: "compression",
  },
  {
    name: "lzma",
    description: "LZMA compression and decompression tool.",
    useCases: ["Create very small files at the cost of slow compression speed"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
    },
    exampleOutputLines: [],
    relatedCommands: ["unlzma", "xz"],
    category: "compression",
  },
  {
    name: "unlzma",
    description: "Decompress files compressed by lzma.",
    useCases: ["Extract .lzma files typically found in old firmware packages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["lzma"],
    category: "compression",
  },
  {
    name: "brotli",
    description: "Brotli compression algorithm tool.",
    useCases: ["Pre-compress static website assets for web servers"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
      "-Z": { description: "Best compression level (11)" },
    },
    exampleOutputLines: [],
    relatedCommands: ["gzip", "zopfli"],
    category: "compression",
  },
  {
    name: "zopfli",
    description: "Deflate-compatible, high density compression tool.",
    useCases: ["Squeeze the absolute maximum compression out of PNG or GZIP files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-c": { description: "Write to standard output" },
    },
    exampleOutputLines: [],
    relatedCommands: ["gzip", "brotli"],
    category: "compression",
  },
  {
    name: "zipinfo",
    description: "List detailed information about a ZIP archive.",
    useCases: ["View compression ratios, dates, and permissions of files inside a ZIP"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-1": { description: "List filenames only, one per line" },
    },
    exampleOutputLines: [],
    relatedCommands: ["unzip"],
    category: "compression",
  },
  {
    name: "atool",
    description: "A script for managing file archives of various types.",
    useCases: ["Extract any type of archive without needing to remember the specific flags"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-x": { description: "Extract the archive" },
      "-a": { description: "Add files to an archive" },
    },
    exampleOutputLines: [],
    relatedCommands: ["aunpack", "tar"],
    category: "compression",
  },
  {
    name: "aunpack",
    description: "Extract archives using atool.",
    useCases: ["Automatically extract a tar.gz, zip, or rar smoothly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["atool", "apack"],
    category: "compression",
  },
  {
    name: "apack",
    description: "Create archives using atool.",
    useCases: ["Quickly package files into the chosen extension seamlessly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["atool"],
    category: "compression",
  },
  {
    name: "als",
    description: "List files in archives using atool.",
    useCases: ["View the contents of any archive format easily"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["atool"],
    category: "compression",
  },
  {
    name: "acat",
    description: "Extract files in archives to standard output.",
    useCases: ["Print the text of a file packed deep inside a tarball without extracting it to disk"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zcat", "atool"],
    category: "compression",
  },
  {
    name: "jar",
    description: "Java archive tool.",
    useCases: ["Extract or create .jar, .war, or .ear Java packages"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "x": { description: "Extract" },
      "c": { description: "Create" },
      "f": { description: "Specify archive filename" },
    },
    exampleOutputLines: [],
    relatedCommands: ["zip"],
    category: "compression",
  },
  {
    name: "arj",
    description: "Archiver for .arj files.",
    useCases: ["Extract legacy MS-DOS ARJ archives"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "x": { description: "Extract files with full pathname" },
    },
    exampleOutputLines: [],
    relatedCommands: ["unrar", "zip"],
    category: "compression",
  },
  {
    name: "lha",
    description: "LZH archive tool.",
    useCases: ["Extract Amiga or Japanese DOS era .lzh archives"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "e": { description: "Extract files" },
    },
    exampleOutputLines: [],
    relatedCommands: ["zip"],
    category: "compression",
  },
  {
    name: "cabextract",
    description: "Program to extract Microsoft Cabinet (.CAB) files.",
    useCases: ["Extract Windows drivers or installer packages on Linux"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Directory to extract files to" },
    },
    exampleOutputLines: [],
    relatedCommands: ["unzip"],
    category: "compression",
  },
  {
    name: "rpm2cpio",
    description: "Convert a Red Hat Package Manager (RPM) archive to a cpio archive.",
    useCases: ["Extract files from an RPM without installing it via yum/dnf"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["cpio", "rpm"],
    category: "compression",
  },
  {
    name: "dpkg-deb",
    description: "Debian package archive tool.",
    useCases: ["Inspect or extract contents of a .deb file locally"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-x": { description: "Extract filesystem tree" },
      "-I": { description: "Show information about a package" },
    },
    exampleOutputLines: [],
    relatedCommands: ["ar", "dpkg"],
    category: "compression",
  },
  {
    name: "pax",
    description: "Read, write, and write lists of the members of archive files.",
    useCases: ["POSIX standard tool to handle tar and cpio archives"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-r": { description: "Read an archive" },
      "-w": { description: "Write an archive" },
    },
    exampleOutputLines: [],
    relatedCommands: ["tar", "cpio"],
    category: "compression",
  },
  {
    name: "shar",
    description: "Create a shell archive.",
    useCases: ["Bundle text files into an executable shell script for extraction"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["unshar", "makeself"],
    category: "compression",
  },
  {
    name: "unshar",
    description: "Unpack a shar archive.",
    useCases: ["Safely strip mail headers and execute a shar archive"],
    isDangerous: false,
    dangerWarning: "Executing untrusted shell archives can run arbitrary code.",
    safeAlternatives: ["Read the script before execution"],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["shar"],
    category: "compression",
  },
  {
    name: "makeself",
    description: "Utility to generate self-extractable archives.",
    useCases: ["Create self-extracting game installers or proprietary software wrappers"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["shar", "tar"],
    category: "compression",
  },
  {
    name: "zpaq",
    description: "Incremental journaling backup utility and archiver.",
    useCases: ["Maintain extremely compressed, deduplicated, versioned backups"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "a": { description: "Add to archive" },
      "x": { description: "Extract" },
    },
    exampleOutputLines: [],
    relatedCommands: ["7z", "tar"],
    category: "compression",
  },
  {
    name: "lrzip",
    description: "Long Range ZIP.",
    useCases: ["Compress extremely large files (ISO, VM images) using massive RAM windows"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
    },
    exampleOutputLines: [],
    relatedCommands: ["rzip", "xz"],
    category: "compression",
  },
  {
    name: "rzip",
    description: "A large-file compression program.",
    useCases: ["Achieve high compression ratios on very large single files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Decompress" },
    },
    exampleOutputLines: [],
    relatedCommands: ["lrzip", "bzip2"],
    category: "compression",
  },
  {
    name: "zmore",
    description: "File perusal filter for crt viewing of compressed text.",
    useCases: ["Read gzipped logs page by page"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zless", "more"],
    category: "compression",
  },
  {
    name: "zdiff",
    description: "Compare compressed files.",
    useCases: ["Diff a gzipped log against an uncompressed log directly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zcmp", "diff"],
    category: "compression",
  },
  {
    name: "zcmp",
    description: "Compare compressed files (calls cmp).",
    useCases: ["Check if two gzipped binaries are identical"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zdiff", "cmp"],
    category: "compression",
  },
  {
    name: "bzcat",
    description: "Decompress files to stdout (bzip2).",
    useCases: ["Print contents of a .bz2 file without extracting it"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zcat", "bzip2"],
    category: "compression",
  },
  {
    name: "bzdiff",
    description: "Compare bzip2 compressed files.",
    useCases: ["Diff two bzip2 log files seamlessly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zdiff"],
    category: "compression",
  },
  {
    name: "bzcmp",
    description: "Compare bzip2 compressed files (calls cmp).",
    useCases: ["Verify identical data inside .bz2 archives"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zcmp"],
    category: "compression",
  },
  {
    name: "bzmore",
    description: "File perusal filter for viewing bzip2 compressed text.",
    useCases: ["Page through a .bz2 file"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zmore"],
    category: "compression",
  },
  {
    name: "xzcat",
    description: "Decompress xz files to standard output.",
    useCases: ["View an .xz compressed file text directly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zcat", "xz"],
    category: "compression",
  },
  {
    name: "xzdiff",
    description: "Compare xz compressed files.",
    useCases: ["Diff .xz archives directly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zdiff"],
    category: "compression",
  },
  {
    name: "xzcmp",
    description: "Compare xz compressed files (calls cmp).",
    useCases: ["Check .xz files byte-by-byte for differences"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["zcmp"],
    category: "compression",
  },
  {
    name: "lzcat",
    description: "Decompress lzma files to standard output.",
    useCases: ["View .lzma log files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["xzcat"],
    category: "compression",
  },
  {
    name: "lzdiff",
    description: "Compare lzma compressed files.",
    useCases: ["Diff two lzma compressed texts"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["xzdiff"],
    category: "compression",
  },
  {
    name: "mksquashfs",
    description: "Create a squashfs filesystem.",
    useCases: ["Create a highly compressed, read-only filesystem image for Live CDs"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-comp": { description: "Select the compression algorithm (e.g., xz, zstd)" },
      "-b": { description: "Set the block size" },
    },
    exampleOutputLines: [],
    relatedCommands: ["unsquashfs", "mkisofs"],
    category: "compression",
  },
  {
    name: "unsquashfs",
    description: "Extract files from a squashfs filesystem.",
    useCases: ["Extract and analyze a Linux Live CD or firmware filesystem"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-d": { description: "Extract to specific directory instead of squashfs-root" },
      "-s": { description: "Show filesystem information only" },
    },
    exampleOutputLines: [],
    relatedCommands: ["mksquashfs"],
    category: "compression",
  },
  {
    name: "mkisofs",
    description: "Create an ISO9660/JOLIET/HFS filesystem.",
    useCases: ["Master a CD/DVD image before burning it"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-o": { description: "Output filename" },
      "-R": { description: "Generate Rock Ridge directory records" },
    },
    exampleOutputLines: [],
    relatedCommands: ["genisoimage", "mksquashfs"],
    category: "compression",
  },
  {
    name: "genisoimage",
    description: "Create an ISO9660 filesystem image (alternative to mkisofs).",
    useCases: ["Generate an ISO image containing backup files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-o": { description: "Set output file" },
      "-J": { description: "Generate Joliet directory records for Windows compatibility" },
    },
    exampleOutputLines: [],
    relatedCommands: ["mkisofs", "isoinfo"],
    category: "compression",
  },
  {
    name: "isoinfo",
    description: "Utility to perform directory like listings of ISO9660 images.",
    useCases: ["Extract a single file from an ISO image", "View ISO contents without mounting"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-l": { description: "Generate a directory listing" },
      "-x": { description: "Extract specified file to standard output" },
    },
    exampleOutputLines: [],
    relatedCommands: ["genisoimage", "mount"],
    category: "compression",
  },
  {
    name: "dump",
    description: "Filesystem backup utility.",
    useCases: ["Filesystem backup"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {
      "-0": { description: "Dump level 0" },
      "-9": { description: "Dump level 9" },
      "-u": { description: "Update /etc/dumpdates" },
      "-f": { description: "Output file/device" },
    },
    exampleOutputLines: [],
    relatedCommands: ["tar", "rsync"],
    category: "compression",
  }
];