import { CommandDef } from "./CommandDef";

export const linuxCmdsNetworkComm: CommandDef[] = [
  {
    name: "ping",
    description: "Send ICMP ECHO_REQUEST to network hosts.",
    useCases: ["Test connectivity to a host"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-c": { description: "Stop after sending a specific number of packets" }, "-i": { description: "Wait interval seconds between sending each packet" } },
    exampleOutputLines: [],
    relatedCommands: ["mtr", "traceroute"],
    category: "network",
  },
  {
    name: "curl",
    description: "Transfer data from or to a server.",
    useCases: ["Download a file", "Test a REST API"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-O": { description: "Save file with remote name" }, "-X": { description: "Specify request method" } },
    exampleOutputLines: [],
    relatedCommands: ["wget", "httpie"],
    category: "network",
  },
  {
    name: "wget",
    description: "Non-interactive network downloader.",
    useCases: ["Download files from the internet", "Mirror a website"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-c": { description: "Resume partial download" } },
    exampleOutputLines: [],
    relatedCommands: ["curl", "aria2c"],
    category: "network",
  },
  {
    name: "ssh",
    description: "OpenSSH remote login client.",
    useCases: ["Log into a remote server securely"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-p": { description: "Specify port" }, "-i": { description: "Identity file (private key)" } },
    exampleOutputLines: [],
    relatedCommands: ["scp", "sftp"],
    category: "network",
  },
  {
    name: "scp",
    description: "Secure copy (remote file copy program).",
    useCases: ["Copy files between hosts securely"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-r": { description: "Recursively copy entire directories" } },
    exampleOutputLines: [],
    relatedCommands: ["rsync", "ssh"],
    category: "network",
  },
  {
    name: "netstat",
    description: "Print network connections, routing tables, interface statistics.",
    useCases: ["See listening ports", "Troubleshoot connections"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-t": { description: "Show TCP" }, "-l": { description: "Listening sockets" } },
    exampleOutputLines: [],
    relatedCommands: ["ss", "lsof"],
    category: "network",
  },
  {
    name: "ss",
    description: "Another utility to investigate sockets (modern netstat).",
    useCases: ["List active connections quickly"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-t": { description: "TCP sockets" }, "-l": { description: "Listening sockets" } },
    exampleOutputLines: [],
    relatedCommands: ["netstat", "ip"],
    category: "network",
  },
  {
    name: "ifconfig",
    description: "Configure a network interface (deprecated, use ip).",
    useCases: ["Check IP address"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-a": { description: "Display all interfaces" } },
    exampleOutputLines: [],
    relatedCommands: ["ip"],
    category: "network",
  },
  {
    name: "ip",
    description: "Show / manipulate routing, network devices, interfaces and tunnels.",
    useCases: ["View IP address", "Change network routing"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-c": { description: "Color output" }, "a": { description: "Address display" } },
    exampleOutputLines: [],
    relatedCommands: ["ifconfig", "route"],
    category: "network",
  },
  {
    name: "nslookup",
    description: "Query Internet name servers interactively.",
    useCases: ["Find IP address of a domain"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["dig", "host"],
    category: "network",
  },
  {
    name: "dig",
    description: "DNS lookup utility.",
    useCases: ["Perform detailed DNS query"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "+short": { description: "Provide terse answer" } },
    exampleOutputLines: [],
    relatedCommands: ["nslookup", "host"],
    category: "network",
  },
  {
    name: "traceroute",
    description: "Print the route packets trace to network host.",
    useCases: ["Find out where network traffic drops"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-n": { description: "Do not resolve IP to domain" } },
    exampleOutputLines: [],
    relatedCommands: ["ping", "mtr"],
    category: "network",
  },
  {
    name: "nc",
    description: "Netcat: Arbitrary TCP and UDP connections and listens.",
    useCases: ["Test open ports", "Simple chat server"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-l": { description: "Listen mode" }, "-z": { description: "Zero-I/O mode (scan)" } },
    exampleOutputLines: [],
    relatedCommands: ["telnet", "socat"],
    category: "network",
  },
  {
    name: "host",
    description: "DNS lookup utility.",
    useCases: ["Quickly resolve domain to IP"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-t": { description: "Specify query type (e.g. MX)" } },
    exampleOutputLines: [],
    relatedCommands: ["dig", "nslookup"],
    category: "network",
  },
  {
    name: "whois",
    description: "Client for the whois directory service.",
    useCases: ["Find domain registrar and owner details"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["dig"],
    category: "network",
  },
  {
    name: "arp",
    description: "Manipulate the system ARP cache.",
    useCases: ["View MAC addresses on local network"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-a": { description: "Show all entries" } },
    exampleOutputLines: [],
    relatedCommands: ["ip"],
    category: "network",
  },
  {
    name: "route",
    description: "Show / manipulate the IP routing table.",
    useCases: ["View default gateway"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-n": { description: "Show numerical addresses" } },
    exampleOutputLines: [],
    relatedCommands: ["ip"],
    category: "network",
  },
  {
    name: "iptables",
    description: "Administration tool for IPv4 packet filtering and NAT.",
    useCases: ["Set up firewall rules", "Block specific IP addresses"],
    isDangerous: true,
    dangerWarning: "Incorrectly modifying iptables can lock you out of a remote server instantly.",
    safeAlternatives: ["Use ufw for a safer, friendlier interface"],
    flags: { "-L": { description: "List rules" }, "-F": { description: "Flush rules" } },
    exampleOutputLines: [],
    relatedCommands: ["nftables", "ufw"],
    category: "network",
  },
  {
    name: "nftables",
    description: "Modern replacement for iptables.",
    useCases: ["Advanced packet filtering"],
    isDangerous: true,
    dangerWarning: "Can lock you out of remote servers if misconfigured.",
    safeAlternatives: ["ufw"],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["iptables", "firewall-cmd"],
    category: "network",
  },
  {
    name: "ufw",
    description: "Uncomplicated Firewall.",
    useCases: ["Easily open or close ports"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "enable": { description: "Turn on firewall" }, "status": { description: "Check status" } },
    exampleOutputLines: [],
    relatedCommands: ["iptables", "firewall-cmd"],
    category: "network",
  },
  {
    name: "firewall-cmd",
    description: "Command line client for firewalld daemon.",
    useCases: ["Manage firewall zones in RHEL/CentOS"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "--list-all": { description: "List current rules" } },
    exampleOutputLines: [],
    relatedCommands: ["ufw", "iptables"],
    category: "network",
  },
  {
    name: "nmap",
    description: "Network exploration tool and security / port scanner.",
    useCases: ["Discover hosts on network", "Check for open ports on a server"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-p": { description: "Specify ports" }, "-sV": { description: "Probe open ports to determine service info" } },
    exampleOutputLines: [],
    relatedCommands: ["nc", "tcpdump"],
    category: "network",
  },
  {
    name: "tcpdump",
    description: "Dump traffic on a network.",
    useCases: ["Capture packets for analysis"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-i": { description: "Specify interface" }, "-w": { description: "Write to file" } },
    exampleOutputLines: [],
    relatedCommands: ["tshark", "wireshark"],
    category: "network",
  },
  {
    name: "tshark",
    description: "Dump and analyze network traffic (terminal Wireshark).",
    useCases: ["Deep packet inspection from CLI"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-r": { description: "Read from capture file" } },
    exampleOutputLines: [],
    relatedCommands: ["tcpdump", "wireshark"],
    category: "network",
  },
  {
    name: "wireshark",
    description: "Interactively dump and analyze network traffic (GUI).",
    useCases: ["Visually analyze pcap files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["tcpdump", "tshark"],
    category: "network",
  },
  {
    name: "rsync",
    description: "Fast, versatile, remote (and local) file-copying tool.",
    useCases: ["Backup directories", "Sync files to remote host"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-a": { description: "Archive mode" }, "-v": { description: "Verbose" }, "-z": { description: "Compress during transfer" } },
    exampleOutputLines: [],
    relatedCommands: ["scp", "cp"],
    category: "network",
  },
  {
    name: "ftp",
    description: "Internet file transfer program.",
    useCases: ["Connect to an FTP server"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["sftp", "curl"],
    category: "network",
  },
  {
    name: "sftp",
    description: "Secure File Transfer Program.",
    useCases: ["Transfer files securely over SSH"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["scp", "ftp"],
    category: "network",
  },
  {
    name: "telnet",
    description: "User interface to the TELNET protocol.",
    useCases: ["Test plain text protocols like SMTP manually"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["nc", "ssh"],
    category: "network",
  },
  {
    name: "socat",
    description: "Multipurpose relay (SOcket CAT).",
    useCases: ["Port forwarding", "Connecting streams"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["nc"],
    category: "network",
  },
  {
    name: "nmcli",
    description: "Command-line tool for controlling NetworkManager.",
    useCases: ["Connect to WiFi from CLI", "Manage network profiles"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "dev": { description: "Device management" }, "con": { description: "Connection management" } },
    exampleOutputLines: [],
    relatedCommands: ["ip", "iwconfig"],
    category: "network",
  },
  {
    name: "iwconfig",
    description: "Configure a wireless network interface.",
    useCases: ["Check WiFi signal strength"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["nmcli"],
    category: "network",
  },
  {
    name: "ethtool",
    description: "Query or control network driver and hardware settings.",
    useCases: ["Check Ethernet link speed"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["ip"],
    category: "network",
  },
  {
    name: "mtr",
    description: "A network diagnostic tool (combines ping and traceroute).",
    useCases: ["Continuously monitor network path performance"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-c": { description: "Report cycle count" } },
    exampleOutputLines: [],
    relatedCommands: ["ping", "traceroute"],
    category: "network",
  },
  {
    name: "aria2c",
    description: "Ultra fast download utility.",
    useCases: ["Download torrents or large files concurrently"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-x": { description: "Max connection per server" } },
    exampleOutputLines: [],
    relatedCommands: ["wget", "curl"],
    category: "network",
  },
  {
    name: "httpie",
    description: "Modern, user-friendly command-line HTTP client for the API era.",
    useCases: ["Test APIs with syntax highlighted output"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["curl"],
    category: "network",
  },
  {
    name: "ab",
    description: "Apache HTTP server benchmarking tool.",
    useCases: ["Load test a web server"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-n": { description: "Number of requests" }, "-c": { description: "Concurrency" } },
    exampleOutputLines: [],
    relatedCommands: ["wrk", "siege"],
    category: "network",
  },
  {
    name: "wrk",
    description: "Modern HTTP benchmarking tool.",
    useCases: ["High-performance load testing"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-t": { description: "Threads" }, "-c": { description: "Connections" } },
    exampleOutputLines: [],
    relatedCommands: ["ab", "siege"],
    category: "network",
  },
  {
    name: "siege",
    description: "HTTP load testing and benchmarking utility.",
    useCases: ["Stress test websites"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-c": { description: "Concurrent users" } },
    exampleOutputLines: [],
    relatedCommands: ["ab", "wrk"],
    category: "network",
  },
  {
    name: "lynx",
    description: "A text-based web browser.",
    useCases: ["Browse simple websites from terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-dump": { description: "Dump webpage text to stdout" } },
    exampleOutputLines: [],
    relatedCommands: ["w3m", "links"],
    category: "network",
  },
  {
    name: "w3m",
    description: "A text-based web browser and pager.",
    useCases: ["Read HTML files in terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["lynx", "elinks"],
    category: "network",
  },
  {
    name: "links",
    description: "Text based web browser with table and frame support.",
    useCases: ["Browse the web without a GUI"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["lynx", "w3m"],
    category: "network",
  },
  {
    name: "elinks",
    description: "Advanced text-based web browser.",
    useCases: ["Terminal web browsing with colors and tabs"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["lynx", "w3m"],
    category: "network",
  },
  {
    name: "ipcalc",
    description: "Perform simple operations on IP addresses and subnets.",
    useCases: ["Calculate subnet masks and broadcast addresses"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["ip"],
    category: "network",
  },
  {
    name: "brctl",
    description: "Ethernet bridge administration.",
    useCases: ["Create a bridge network for virtual machines"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["ip"],
    category: "network",
  },
  {
    name: "tunctl",
    description: "Create and manage TUN/TAP network interfaces.",
    useCases: ["Setup virtual network interfaces"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["ip"],
    category: "network",
  },
  {
    name: "wpa_supplicant",
    description: "Wi-Fi Protected Access client and IEEE 802.1X supplicant.",
    useCases: ["Connect to WPA-secured wireless networks from terminal"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-B": { description: "Run in background" } },
    exampleOutputLines: [],
    relatedCommands: ["iwconfig", "nmcli"],
    category: "network",
  },
  {
    name: "hostnamectl",
    description: "Control the system hostname.",
    useCases: ["Change the computer's network name permanently"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "set-hostname": { description: "Set the system hostname" } },
    exampleOutputLines: [],
    relatedCommands: ["hostname"],
    category: "network",
  },
  {
    name: "resolvectl",
    description: "Resolve domain names, IPV4 and IPv6 addresses, DNS resource records, and services.",
    useCases: ["Flush DNS cache", "Query DNS via systemd-resolved"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "flush-caches": { description: "Flush all local DNS caches" } },
    exampleOutputLines: [],
    relatedCommands: ["dig", "nslookup"],
    category: "network",
  },
  {
    name: "networkctl",
    description: "Query the status of network links.",
    useCases: ["Check systemd-networkd status"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "status": { description: "Show link status" } },
    exampleOutputLines: [],
    relatedCommands: ["ip"],
    category: "network",
  },
  {
    name: "lftp",
    description: "Sophisticated file transfer program.",
    useCases: ["Transfer files"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-e": { description: "Execute command" }, "-u": { description: "User,password" }, "-f": { description: "Execute commands from file" }, "-c": { description: "Execute command and exit" } },
    exampleOutputLines: [],
    relatedCommands: ["ftp", "sftp"],
    category: "network",
  }
];