import { CommandDef } from "./CommandDef";

export const linuxCmdsDisk: CommandDef[] = [
  {
    name: "mount",
    description: "Mount a filesystem.",
    useCases: ["Attach a hard drive to a directory"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-a": { description: "Mount all filesystems in fstab" } },
    exampleOutputLines: [],
    relatedCommands: ["umount", "lsblk"],
    category: "disk",
  },
  {
    name: "umount",
    description: "Unmount file systems.",
    useCases: ["Safely eject a drive"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-l": { description: "Lazy unmount" } },
    exampleOutputLines: [],
    relatedCommands: ["mount"],
    category: "disk",
  },
  {
    name: "fdisk",
    description: "Manipulate disk partition table.",
    useCases: ["Create new partitions"],
    isDangerous: true,
    dangerWarning: "Modifying partitions can lead to permanent data loss if you select the wrong drive.",
    safeAlternatives: ["Verify drive with lsblk"],
    flags: { "-l": { description: "List partition tables" } },
    exampleOutputLines: [],
    relatedCommands: ["parted", "mkfs"],
    category: "disk",
  },
  {
    name: "parted",
    description: "A partition manipulation program.",
    useCases: ["Create GPT partition tables on drives >2TB"],
    isDangerous: true,
    dangerWarning: "Can destroy data if partitions are resized incorrectly.",
    safeAlternatives: [],
    flags: { "-l": { description: "List partitions" } },
    exampleOutputLines: [],
    relatedCommands: ["fdisk"],
    category: "disk",
  },
  {
    name: "mkfs",
    description: "Build a Linux filesystem.",
    useCases: ["Format a newly created partition to ext4"],
    isDangerous: true,
    dangerWarning: "Formatting deletes all data currently existing on the partition.",
    safeAlternatives: [],
    flags: { "-t": { description: "Specify filesystem type" } },
    exampleOutputLines: [],
    relatedCommands: ["fdisk", "fsck"],
    category: "disk",
  },
  {
    name: "fsck",
    description: "Check and repair a Linux filesystem.",
    useCases: ["Fix corruption after a sudden power loss"],
    isDangerous: true,
    dangerWarning: "Running fsck on a mounted filesystem can cause severe data corruption.",
    safeAlternatives: ["Unmount the drive first"],
    flags: { "-y": { description: "Automatically repair" } },
    exampleOutputLines: [],
    relatedCommands: ["tune2fs", "e2fsck"],
    category: "disk",
  },
  {
    name: "blkid",
    description: "Locate/print block device attributes.",
    useCases: ["Find the UUID of a drive to put into /etc/fstab"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["lsblk"],
    category: "disk",
  },
  {
    name: "smartctl",
    description: "Control and Monitor Utility for SMART Disks.",
    useCases: ["Check hard drive health and predict failure"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-a": { description: "Print all SMART information" } },
    exampleOutputLines: [],
    relatedCommands: ["hdparm"],
    category: "disk",
  },
  {
    name: "hdparm",
    description: "Get/set SATA/IDE device parameters.",
    useCases: ["Benchmark drive read speeds"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-tT": { description: "Perform device read timings" } },
    exampleOutputLines: [],
    relatedCommands: ["smartctl"],
    category: "disk",
  },
  {
    name: "tune2fs",
    description: "Adjust tunable filesystem parameters on ext2/ext3/ext4 filesystems.",
    useCases: ["Change mount counts or reserved blocks"],
    isDangerous: false,
    dangerWarning: null,
    safeAlternatives: [],
    flags: { "-m": { description: "Set reserved blocks percentage" } },
    exampleOutputLines: [],
    relatedCommands: ["fsck", "e2fsck"],
    category: "disk",
  },
  {
    name: "e2fsck",
    description: "Check a Linux ext2/ext3/ext4 file system.",
    useCases: ["Deep repair of ext4 partitions"],
    isDangerous: true,
    dangerWarning: "Do not run on mounted partitions.",
    safeAlternatives: [],
    flags: {},
    exampleOutputLines: [],
    relatedCommands: ["fsck"],
    category: "disk",
  }
];