import { ExampleOutputLine } from "./linuxCmdExampleOutputs";

export const linuxCmdExampleOutputs6: Record<string, ExampleOutputLine[]> = {
  nl: [
    {
      line: "     1  127.0.0.1       localhost",
      segments: [
        { text: "     1  ", explanation: "Line number automatically generated by nl" },
        { text: "127.0.0.1       localhost", explanation: "Localhost entry mapping" }
      ]
    },
    {
      line: "     2  127.0.1.1       devbox",
      segments: [
        { text: "     2  ", explanation: "Line number automatically generated by nl" },
        { text: "127.0.1.1       devbox", explanation: "Hostname mapping for the current machine" }
      ]
    },
    {
      line: "     3  ",
      segments: [
        { text: "     3  ", explanation: "Blank line numbered because of -b a flag (number all lines)" }
      ]
    },
    {
      line: "     4  # The following lines are desirable for IPv6 capable hosts",
      segments: [
        { text: "     4  ", explanation: "Line number" },
        { text: "# The following lines are desirable for IPv6 capable hosts", explanation: "A commented line in the hosts file" }
      ]
    },
    {
      line: "     5  ::1     ip6-localhost ip6-loopback",
      segments: [
        { text: "     5  ", explanation: "Line number" },
        { text: "::1     ip6-localhost ip6-loopback", explanation: "IPv6 loopback entry" }
      ]
    },
    {
      line: "     6  fe00::0 ip6-localnet",
      segments: [
        { text: "     6  ", explanation: "Line number" },
        { text: "fe00::0 ip6-localnet", explanation: "IPv6 localnet entry" }
      ]
    }
  ],
  env: [
    {
      line: "USER=developer",
      segments: [
        { text: "USER", explanation: "Environment variable controlling the current logged-in username" },
        { text: "=", explanation: "Assignment" },
        { text: "developer", explanation: "The active user name" }
      ]
    },
    {
      line: "HOME=/home/developer",
      segments: [
        { text: "HOME", explanation: "Environment variable controlling the default home directory path" },
        { text: "=", explanation: "Assignment" },
        { text: "/home/developer", explanation: "The path to the home directory" }
      ]
    },
    {
      line: "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      segments: [
        { text: "PATH", explanation: "Environment variable controlling where the shell looks for executable commands" },
        { text: "=", explanation: "Assignment" },
        { text: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", explanation: "Colon-separated list of directories to search" }
      ]
    },
    {
      line: "SHELL=/bin/bash",
      segments: [
        { text: "SHELL", explanation: "Environment variable controlling the user's default login shell program" },
        { text: "=", explanation: "Assignment" },
        { text: "/bin/bash", explanation: "Path to the bash executable" }
      ]
    },
    {
      line: "TERM=xterm-256color",
      segments: [
        { text: "TERM", explanation: "Environment variable controlling the terminal emulator capabilities" },
        { text: "=", explanation: "Assignment" },
        { text: "xterm-256color", explanation: "Indicates support for 256 colors" }
      ]
    },
    {
      line: "LANG=en_US.UTF-8",
      segments: [
        { text: "LANG", explanation: "Environment variable controlling the system locale and language settings" },
        { text: "=", explanation: "Assignment" },
        { text: "en_US.UTF-8", explanation: "US English with UTF-8 character encoding" }
      ]
    },
    {
      line: "EDITOR=vim",
      segments: [
        { text: "EDITOR", explanation: "Environment variable controlling the default text editor for command-line tools" },
        { text: "=", explanation: "Assignment" },
        { text: "vim", explanation: "Vim editor is set as default" }
      ]
    },
    {
      line: "SSH_CLIENT=192.168.1.50 54321 22",
      segments: [
        { text: "SSH_CLIENT", explanation: "Environment variable controlling the origin of the SSH connection" },
        { text: "=", explanation: "Assignment" },
        { text: "192.168.1.50 54321 22", explanation: "Client IP, client port, and server port" }
      ]
    },
    {
      line: "PWD=/home/developer/projects",
      segments: [
        { text: "PWD", explanation: "Environment variable controlling the current Print Working Directory" },
        { text: "=", explanation: "Assignment" },
        { text: "/home/developer/projects", explanation: "Current active folder path" }
      ]
    },
    {
      line: "LOGNAME=developer",
      segments: [
        { text: "LOGNAME", explanation: "Environment variable controlling the login name (often matches USER)" },
        { text: "=", explanation: "Assignment" },
        { text: "developer", explanation: "The login name" }
      ]
    }
  ],
  useradd: [
    {
      line: "(no output)",
      segments: [
        { text: "(no output)", explanation: "useradd silently creates the user account on success. Use 'id newuser' to verify the account was created." }
      ]
    }
  ],
  ps: [
    {
      line: "USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND",
      segments: [
        { text: "USER         ", explanation: "The user running the process" },
        { text: "PID ", explanation: "Process ID" },
        { text: "%CPU %MEM    ", explanation: "CPU and Memory usage percentage" },
        { text: "VSZ   RSS ", explanation: "Virtual and Resident memory sizes" },
        { text: "TTY      ", explanation: "Terminal attached to the process (? means no terminal)" },
        { text: "STAT ", explanation: "Process state code" },
        { text: "START   ", explanation: "When the process started" },
        { text: "TIME ", explanation: "Total CPU time used" },
        { text: "COMMAND", explanation: "The command that started the process" }
      ]
    },
    {
      line: "root           1  0.0  0.1 168512 12480 ?        Ss   Oct01   1:12 /sbin/init",
      segments: [
        { text: "root           1  0.0  0.1 168512 12480 ?        Ss   Oct01   1:12 ", explanation: "Process metrics for PID 1" },
        { text: "/sbin/init", explanation: "PID 1 is the first process started by the system (systemd or init)" }
      ]
    },
    {
      line: "root         452  0.0  0.0      0     0 ?        I    Oct01   0:05 [kworker/0:1-events]",
      segments: [
        { text: "root         452  0.0  0.0      0     0 ?        I    Oct01   0:05 ", explanation: "Process metrics" },
        { text: "[kworker/0:1-events]", explanation: "Brackets indicate a kernel worker thread, not a regular user process" }
      ]
    },
    {
      line: "root         890  0.0  0.1  15480  8740 ?        Ss   Oct01   0:02 sshd: /usr/sbin/sshd -D",
      segments: [
        { text: "root         890  0.0  0.1  15480  8740 ?        Ss   Oct01   0:02 ", explanation: "Process metrics" },
        { text: "sshd: /usr/sbin/sshd -D", explanation: "The SSH daemon listening for incoming connections" }
      ]
    },
    {
      line: "www-data     912  1.2  0.3 145620 24500 ?        S    Oct01   5:23 nginx: worker process",
      segments: [
        { text: "www-data     912  1.2  0.3 145620 24500 ?        S    Oct01   5:23 ", explanation: "Process metrics" },
        { text: "nginx: worker process", explanation: "Nginx web server worker process running as www-data user" }
      ]
    },
    {
      line: "postgres    1105  0.5  1.8 356100 145000 ?       S    Oct01  12:45 postgres: main process",
      segments: [
        { text: "postgres    1105  0.5  1.8 356100 145000 ?       S    Oct01  12:45 ", explanation: "Process metrics" },
        { text: "postgres: main process", explanation: "PostgreSQL database main process" }
      ]
    },
    {
      line: "nodeuser    1540  3.4  1.5 856100 125400 ?       Sl   Oct01  45:12 node /app/server.js",
      segments: [
        { text: "nodeuser    1540  3.4  1.5 856100 125400 ?       Sl   Oct01  45:12 ", explanation: "Process metrics" },
        { text: "node /app/server.js", explanation: "A running Node.js application" }
      ]
    },
    {
      line: "root        2100  0.0  0.0   8536  3200 ?        Ss   Oct01   0:10 /usr/sbin/cron -f",
      segments: [
        { text: "root        2100  0.0  0.0   8536  3200 ?        Ss   Oct01   0:10 ", explanation: "Process metrics" },
        { text: "/usr/sbin/cron -f", explanation: "The cron daemon responsible for scheduled tasks" }
      ]
    },
    {
      line: "developer   4200  0.0  0.1  12048  5100 pts/0    Ss   14:30   0:00 -bash",
      segments: [
        { text: "developer   4200  0.0  0.1  12048  5100 pts/0    Ss   14:30   0:00 ", explanation: "Process metrics" },
        { text: "-bash", explanation: "The user's interactive login shell" }
      ]
    },
    {
      line: "developer   4250  0.0  0.0  10760  3400 pts/0    R+   14:32   0:00 ps aux",
      segments: [
        { text: "developer   4250  0.0  0.0  10760  3400 pts/0    R+   14:32   0:00 ", explanation: "Process metrics showing state R+ (running in foreground)" },
        { text: "ps aux", explanation: "The ps command itself that generated this output" }
      ]
    }
  ],
  vi: [
    {
      line: "This is the content of the file.",
      segments: [{ text: "This is the content of the file.", explanation: "First line of file content" }]
    },
    {
      line: "Second line of the file.",
      segments: [{ text: "Second line of the file.", explanation: "Second line of file content" }]
    },
    {
      line: "~",
      segments: [{ text: "~", explanation: "Tilde marks empty lines below the actual file content" }]
    },
    {
      line: "~",
      segments: [{ text: "~", explanation: "Empty line" }]
    },
    {
      line: "~",
      segments: [{ text: "~", explanation: "Empty line" }]
    },
    {
      line: "~",
      segments: [{ text: "~", explanation: "Empty line" }]
    },
    {
      line: "~",
      segments: [{ text: "~", explanation: "Empty line" }]
    },
    {
      line: "~",
      segments: [{ text: "~", explanation: "Empty line" }]
    },
    {
      line: "\"myfile.txt\" 2L, 45C",
      segments: [{ text: "\"myfile.txt\" 2L, 45C", explanation: "Status bar shows filename, line count (2L), and character count (45C). Press :q! to quit without saving, or :wq to save and quit." }]
    }
  ],
  vim: [
    {
      line: "~                                                         ",
      segments: [{ text: "~                                                         ", explanation: "Empty line marked by tilde" }]
    },
    {
      line: "~                    VIM - Vi IMproved                    ",
      segments: [{ text: "~                    VIM - Vi IMproved                    ", explanation: "VIM splash screen banner" }]
    },
    {
      line: "~                                                         ",
      segments: [{ text: "~                                                         ", explanation: "Empty line" }]
    },
    {
      line: "~                     version 9.0                         ",
      segments: [{ text: "~                     version 9.0                         ", explanation: "VIM version information" }]
    },
    {
      line: "~               by Bram Moolenaar et al.                  ",
      segments: [{ text: "~               by Bram Moolenaar et al.                  ", explanation: "Author credits" }]
    },
    {
      line: "~                                                         ",
      segments: [{ text: "~                                                         ", explanation: "Empty line" }]
    },
    {
      line: "~          type  :q<Enter>          to exit               ",
      segments: [{ text: "~          type  :q<Enter>          to exit               ", explanation: "Instructions on how to exit the editor" }]
    },
    {
      line: "~          type  :help<Enter>       for on-line help      ",
      segments: [{ text: "~          type  :help<Enter>       for on-line help      ", explanation: "Instructions on getting help" }]
    },
    {
      line: "~          type  :help version9<Enter>  for version info  ",
      segments: [{ text: "~          type  :help version9<Enter>  for version info  ", explanation: "Instructions for version details" }]
    },
    {
      line: "~                                                         ",
      segments: [{ text: "~                                                         ", explanation: "Empty line" }]
    },
    {
      line: "~                                                         ",
      segments: [{ text: "~                                                         ", explanation: "Empty line" }]
    },
    {
      line: "0,0-1         All",
      segments: [{ text: "0,0-1         All", explanation: "Status bar showing cursor position" }]
    }
  ],
  emacs: [
    {
      line: "Welcome to GNU Emacs, one component of the GNU/Linux operating system.",
      segments: [{ text: "Welcome to GNU Emacs, one component of the GNU/Linux operating system.", explanation: "Emacs splash screen welcome message" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "Get help           C-h  (Hold down CTRL and press h)",
      segments: [{ text: "Get help           C-h  (Hold down CTRL and press h)", explanation: "Instruction on getting help. C- stands for Ctrl." }]
    },
    {
      line: "Emacs manual       C-h r",
      segments: [{ text: "Emacs manual       C-h r", explanation: "Shortcut for the Emacs manual" }]
    },
    {
      line: "Emacs tutorial     C-h t",
      segments: [{ text: "Emacs tutorial     C-h t", explanation: "Shortcut for the interactive tutorial" }]
    },
    {
      line: "Undo changes       C-x u",
      segments: [{ text: "Undo changes       C-x u", explanation: "Shortcut to undo modifications" }]
    },
    {
      line: "Exit Emacs         C-x C-c",
      segments: [{ text: "Exit Emacs         C-x C-c", explanation: "Shortcut to quit the editor safely" }]
    }
  ],
  nano: [
    {
      line: "  GNU nano 6.2                    myfile.txt                              ",
      segments: [{ text: "  GNU nano 6.2                    myfile.txt                              ", explanation: "Header showing the editor version and the active file name" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "This is the content of the file.",
      segments: [{ text: "This is the content of the file.", explanation: "File content line" }]
    },
    {
      line: "Second line of the file.",
      segments: [{ text: "Second line of the file.", explanation: "File content line" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "                            [ Read 2 lines ]",
      segments: [{ text: "                            [ Read 2 lines ]", explanation: "Confirmation message when opening the file" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "^G Help    ^O Write Out ^W Where Is  ^K Cut       ^J Justify",
      segments: [{ text: "^G Help    ^O Write Out ^W Where Is  ^K Cut       ^J Justify", explanation: "Shortcut bar at the bottom. ^ means Ctrl. Press Ctrl+O to save." }]
    },
    {
      line: "^X Exit    ^R Read File  ^\\ Replace   ^U Paste     ^T Execute",
      segments: [{ text: "^X Exit    ^R Read File  ^\\ Replace   ^U Paste     ^T Execute", explanation: "More shortcuts. Press Ctrl+X to exit." }]
    }
  ],
  vimtutor: [
    {
      line: "===============================================================================",
      segments: [{ text: "===============================================================================", explanation: "Decorative banner top" }]
    },
    {
      line: "=    W e l c o m e   t o   t h e   V I M   T u t o r    -    Version 1.7     =",
      segments: [{ text: "=    W e l c o m e   t o   t h e   V I M   T u t o r    -    Version 1.7     =", explanation: "Welcome banner and version" }]
    },
    {
      line: "===============================================================================",
      segments: [{ text: "===============================================================================", explanation: "Decorative banner bottom" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "     Vim is a very powerful editor that has many commands, too many to",
      segments: [{ text: "     Vim is a very powerful editor that has many commands, too many to", explanation: "Tutor introduction" }]
    },
    {
      line: "     explain in a tutor such as this.  This tutor is designed to describe",
      segments: [{ text: "     explain in a tutor such as this.  This tutor is designed to describe", explanation: "Tutor introduction" }]
    },
    {
      line: "     enough of the commands that you will be able to easily use Vim as",
      segments: [{ text: "     enough of the commands that you will be able to easily use Vim as", explanation: "Tutor introduction" }]
    },
    {
      line: "     an all-purpose editor.",
      segments: [{ text: "     an all-purpose editor.", explanation: "Tutor introduction" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "     The approximate time required to complete the tutor is 25-30 minutes,",
      segments: [{ text: "     The approximate time required to complete the tutor is 25-30 minutes,", explanation: "Time estimate" }]
    },
    {
      line: "     depending upon how much time is spent with experimentation.",
      segments: [{ text: "     depending upon how much time is spent with experimentation.", explanation: "Time estimate" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "     Type  :q<Enter>  to exit at any time.",
      segments: [{ text: "     Type  :q<Enter>  to exit at any time.", explanation: "Exit instruction" }]
    }
  ],
  gedit: [
    {
      line: "(gedit:12345): Gtk-WARNING **: 14:32:05.123: Theme parsing error: gtk.css:1:0: Failed to import",
      segments: [
        { text: "(gedit:12345): Gtk-WARNING **: 14:32:05.123: Theme parsing error: gtk.css:1:0: Failed to import", explanation: "gedit is a graphical editor - this is a common non-critical GTK theme warning, the editor opens in a GUI window." }
      ]
    }
  ],
  micro: [
    {
      line: "myfile.txt",
      segments: [{ text: "myfile.txt", explanation: "Filename tab at the top of the interface" }]
    },
    {
      line: "This is the content of the file.",
      segments: [{ text: "This is the content of the file.", explanation: "File content line" }]
    },
    {
      line: "Second line of the file.",
      segments: [{ text: "Second line of the file.", explanation: "File content line" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty space" }]
    },
    {
      line: "> Ctrl+S: Save | Ctrl+Q: Quit | Ctrl+F: Find | Ctrl+Z: Undo",
      segments: [{ text: "> Ctrl+S: Save | Ctrl+Q: Quit | Ctrl+F: Find | Ctrl+Z: Undo", explanation: "Familiar keyboard shortcuts at the bottom. Press Ctrl+Q to quit, Ctrl+S to save." }]
    }
  ],
  code: [
    {
      line: "(no output)",
      segments: [
        { text: "(no output)", explanation: "VS Code opens in a separate graphical window. The terminal returns to the prompt immediately unless --wait is used." }
      ]
    }
  ],
  source: [
    {
      line: "(no output)",
      segments: [
        { text: "(no output)", explanation: "source executes the file in the current shell. Changes to variables and functions take effect immediately without any output." }
      ]
    }
  ],
  set: [
    {
      line: "BASH=/usr/bin/bash",
      segments: [{ text: "BASH=/usr/bin/bash", explanation: "The path to the Bash executable" }]
    },
    {
      line: "BASHOPTS=checkwinsize:cmdhist:complete_fullquote:expand_aliases:extglob:extquote",
      segments: [{ text: "BASHOPTS=checkwinsize:cmdhist:complete_fullquote:expand_aliases:extglob:extquote", explanation: "Current active Bash options" }]
    },
    {
      line: "BASH_VERSION='5.1.16(1)-release'",
      segments: [{ text: "BASH_VERSION='5.1.16(1)-release'", explanation: "The version of Bash running" }]
    },
    {
      line: "COLUMNS=120",
      segments: [{ text: "COLUMNS=120", explanation: "Terminal width in columns" }]
    },
    {
      line: "HISTFILE=/home/developer/.bash_history",
      segments: [{ text: "HISTFILE=/home/developer/.bash_history", explanation: "Where command history is saved" }]
    },
    {
      line: "HISTFILESIZE=2000",
      segments: [{ text: "HISTFILESIZE=2000", explanation: "Max lines allowed in the history file" }]
    },
    {
      line: "HISTSIZE=1000",
      segments: [{ text: "HISTSIZE=1000", explanation: "Max lines allowed in history memory" }]
    },
    {
      line: "HOME=/home/developer",
      segments: [{ text: "HOME=/home/developer", explanation: "Current user's home directory" }]
    },
    {
      line: "HOSTNAME=devbox",
      segments: [{ text: "HOSTNAME=devbox", explanation: "System hostname" }]
    },
    {
      line: "IFS=$' \\t\\n'",
      segments: [{ text: "IFS=$' \\t\\n'", explanation: "Internal Field Separator, usually space, tab, and newline" }]
    },
    {
      line: "LINES=40",
      segments: [{ text: "LINES=40", explanation: "Terminal height in lines" }]
    },
    {
      line: "PATH=/usr/local/bin:/usr/bin:/bin",
      segments: [{ text: "PATH=/usr/local/bin:/usr/bin:/bin", explanation: "Directories to search for executable commands" }]
    },
    {
      line: "PS1='\\u@\\h:\\w\\$ '",
      segments: [{ text: "PS1='\\u@\\h:\\w\\$ '", explanation: "Primary prompt string formatting" }]
    },
    {
      line: "PWD=/home/developer/projects",
      segments: [{ text: "PWD=/home/developer/projects", explanation: "Present Working Directory" }]
    },
    {
      line: "SHELL=/bin/bash",
      segments: [{ text: "SHELL=/bin/bash", explanation: "Default login shell path" }]
    },
    {
      line: "TERM=xterm-256color",
      segments: [{ text: "TERM=xterm-256color", explanation: "Terminal emulator type" }]
    },
    {
      line: "USER=developer",
      segments: [{ text: "USER=developer", explanation: "Currently logged in user" }]
    }
  ],
  unset: [
    {
      line: "(no output)",
      segments: [
        { text: "(no output)", explanation: "unset silently removes the variable or function. The variable will no longer be accessible." }
      ]
    }
  ],
  readonly: [
    {
      line: "(no output)",
      segments: [
        { text: "(no output)", explanation: "readonly silently marks variables as read-only on success, preventing them from being modified or unset." }
      ]
    }
  ],
  getfacl: [
    {
      line: "# file: project/",
      segments: [{ text: "# file: project/", explanation: "File metadata showing the path" }]
    },
    {
      line: "# owner: developer",
      segments: [{ text: "# owner: developer", explanation: "File metadata showing the owner" }]
    },
    {
      line: "# group: developers",
      segments: [{ text: "# group: developers", explanation: "File metadata showing the group" }]
    },
    {
      line: "# flags: -s-",
      segments: [{ text: "# flags: -s-", explanation: "File metadata showing special flags (e.g., setuid/setgid)" }]
    },
    {
      line: "user::rwx",
      segments: [{ text: "user::rwx", explanation: "Base permissions for the owner (read, write, execute)" }]
    },
    {
      line: "user:alice:r-x",
      segments: [{ text: "user:alice:r-x", explanation: "Named user ACL entry giving Alice read and execute access" }]
    },
    {
      line: "group::r-x",
      segments: [{ text: "group::r-x", explanation: "Base permissions for the group" }]
    },
    {
      line: "mask::r-x",
      segments: [{ text: "mask::r-x", explanation: "Mask representing the maximum effective permissions for named users and groups" }]
    },
    {
      line: "other::---",
      segments: [{ text: "other::---", explanation: "Base permissions for others (completely denied)" }]
    }
  ],
  lsattr: [
    {
      line: "--------------e------- ./file1.txt",
      segments: [
        { text: "--------------", explanation: "Dashes indicate unset attributes" },
        { text: "e", explanation: "Extent format attribute (used for mapping blocks on ext4)" },
        { text: "------- ", explanation: "More unset attributes" },
        { text: "./file1.txt", explanation: "The target file" }
      ]
    },
    {
      line: "----i---------e------- ./important.conf",
      segments: [
        { text: "----", explanation: "Unset attributes" },
        { text: "i", explanation: "Immutable attribute (the file cannot be modified, deleted, or renamed even by root)" },
        { text: "---------e------- ", explanation: "Extent format and unset attributes" },
        { text: "./important.conf", explanation: "The target file" }
      ]
    }
  ],
  namei: [
    {
      line: "f: /var/log/syslog",
      segments: [
        { text: "f: ", explanation: "Indicates the target is a file" },
        { text: "/var/log/syslog", explanation: "The full file path being analyzed" }
      ]
    },
    {
      line: " drwxr-xr-x root root /",
      segments: [
        { text: " drwxr-xr-x ", explanation: "Permissions for the directory" },
        { text: "root root ", explanation: "Owner and group" },
        { text: "/", explanation: "The root directory. Namei shows permissions at each level to show how access can be denied at any point." }
      ]
    },
    {
      line: " drwxr-xr-x root root var",
      segments: [{ text: " drwxr-xr-x root root var", explanation: "Permissions for the /var directory" }]
    },
    {
      line: " drwxrwxr-x root syslog log",
      segments: [{ text: " drwxrwxr-x root syslog log", explanation: "Permissions for the /var/log directory" }]
    },
    {
      line: " -rw-r----- syslog adm  syslog",
      segments: [{ text: " -rw-r----- syslog adm  syslog", explanation: "Final file permissions for /var/log/syslog" }]
    }
  ],
  finger: [
    {
      line: "Login: developer                        Name: Dev User",
      segments: [{ text: "Login: developer                        Name: Dev User", explanation: "User's login ID and full real name" }]
    },
    {
      line: "Directory: /home/developer              Shell: /bin/bash",
      segments: [{ text: "Directory: /home/developer              Shell: /bin/bash", explanation: "User's home directory path and login shell" }]
    },
    {
      line: "On since Thu Oct 12 10:00 (UTC) on pts/0 from 192.168.1.50",
      segments: [{ text: "On since Thu Oct 12 10:00 (UTC) on pts/0 from 192.168.1.50", explanation: "Active login session start time, terminal line, and remote origin IP" }]
    },
    {
      line: "   5 minutes 30 seconds idle",
      segments: [{ text: "   5 minutes 30 seconds idle", explanation: "How long the user has been inactive" }]
    },
    {
      line: "No mail.",
      segments: [{ text: "No mail.", explanation: "User's system mail status" }]
    },
    {
      line: "No Plan.",
      segments: [{ text: "No Plan.", explanation: "Indicates the user has not created a ~/.plan file" }]
    }
  ],
  ac: [
    {
      line: "        Oct 10    total        8.50",
      segments: [{ text: "        Oct 10    total        8.50", explanation: "Total connection hours for Oct 10" }]
    },
    {
      line: "        Oct 11    total        9.25",
      segments: [{ text: "        Oct 11    total        9.25", explanation: "Total connection hours for Oct 11" }]
    },
    {
      line: "        Oct 12    total        4.75",
      segments: [{ text: "        Oct 12    total        4.75", explanation: "Total connection hours for Oct 12" }]
    },
    {
      line: "        Today     total       22.50",
      segments: [{ text: "        Today     total       22.50", explanation: "Cumulative connection hours spanning these days" }]
    }
  ],
  faillock: [
    {
      line: "developer:",
      segments: [{ text: "developer:", explanation: "The user account being checked" }]
    },
    {
      line: "When                 Type  Source                                  Valid",
      segments: [{ text: "When                 Type  Source                                  Valid", explanation: "Table header indicating timestamp, authentication type, IP origin, and validity" }]
    },
    {
      line: "2023-10-12 09:15:30  AUTH  192.168.1.100                             V",
      segments: [{ text: "2023-10-12 09:15:30  AUTH  192.168.1.100                             V", explanation: "A failed login attempt from this IP address" }]
    },
    {
      line: "2023-10-12 09:15:45  AUTH  192.168.1.100                             V",
      segments: [{ text: "2023-10-12 09:15:45  AUTH  192.168.1.100                             V", explanation: "A failed login attempt from this IP address" }]
    },
    {
      line: "2023-10-12 09:16:02  AUTH  192.168.1.100                             V",
      segments: [{ text: "2023-10-12 09:16:02  AUTH  192.168.1.100                             V", explanation: "A failed login attempt from this IP address" }]
    }
  ],
  visudo: [
    {
      line: "## sudoers file.",
      segments: [{ text: "## sudoers file.", explanation: "Opened in editor with syntax checking on exit" }]
    },
    {
      line: "##",
      segments: [{ text: "##", explanation: "Comment line" }]
    },
    {
      line: "## This file MUST be edited with the 'visudo' command as root.",
      segments: [{ text: "## This file MUST be edited with the 'visudo' command as root.", explanation: "Warning comment" }]
    },
    {
      line: "##",
      segments: [{ text: "##", explanation: "Comment line" }]
    },
    {
      line: "## See the man page for details on how to write a sudoers file.",
      segments: [{ text: "## See the man page for details on how to write a sudoers file.", explanation: "Comment line" }]
    },
    {
      line: "##",
      segments: [{ text: "##", explanation: "Comment line" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "# Host alias specification",
      segments: [{ text: "# Host alias specification", explanation: "Section header" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "# User privilege specification",
      segments: [{ text: "# User privilege specification", explanation: "Section header" }]
    },
    {
      line: "root    ALL=(ALL:ALL) ALL",
      segments: [{ text: "root    ALL=(ALL:ALL) ALL", explanation: "Rule giving root user all privileges" }]
    },
    {
      line: "%sudo   ALL=(ALL:ALL) ALL",
      segments: [{ text: "%sudo   ALL=(ALL:ALL) ALL", explanation: "Rule giving users in the sudo group all privileges" }]
    }
  ],
  fold: [
    {
      line: "This is a very long line that has been",
      segments: [{ text: "This is a very long line that has been", explanation: "Text wrapped at the specified column boundary" }]
    },
    {
      line: " wrapped at the specified column width",
      segments: [{ text: " wrapped at the specified column width", explanation: "Continued wrapped line" }]
    },
    {
      line: " using the fold command to ensure readab",
      segments: [{ text: " using the fold command to ensure readab", explanation: "Continued wrapped line" }]
    },
    {
      line: "ility in narrow terminal windows.",
      segments: [{ text: "ility in narrow terminal windows.", explanation: "Continued wrapped line" }]
    }
  ],
  groff: [
    {
      line: "LS(1)                            User Commands                           LS(1)",
      segments: [{ text: "LS(1)                            User Commands                           LS(1)", explanation: "Formatted man page output header (similar to what man ls | head shows)" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "NAME",
      segments: [{ text: "NAME", explanation: "Section header" }]
    },
    {
      line: "       ls - list directory contents",
      segments: [{ text: "       ls - list directory contents", explanation: "Command name and brief description" }]
    },
    {
      line: "",
      segments: [{ text: "", explanation: "Empty line" }]
    },
    {
      line: "SYNOPSIS",
      segments: [{ text: "SYNOPSIS", explanation: "Section header" }]
    },
    {
      line: "       ls [OPTION]... [FILE]...",
      segments: [{ text: "       ls [OPTION]... [FILE]...", explanation: "Command usage syntax" }]
    }
  ],
  pgrep: [
    {
      line: " 890",
      segments: [{ text: " 890", explanation: "PID of a process matching the pattern. Use -l to also show process names." }]
    },
    {
      line: "1105",
      segments: [{ text: "1105", explanation: "PID of another matching process" }]
    },
    {
      line: "1540",
      segments: [{ text: "1540", explanation: "PID of another matching process" }]
    }
  ],
  pkill: [
    {
      line: "(no output)",
      segments: [
        { text: "(no output)", explanation: "pkill silently sends the signal to matching processes. Use pgrep first to verify which processes will be affected." }
      ]
    }
  ],
  pidof: [
    {
      line: "890 1105",
      segments: [
        { text: "890 1105", explanation: "PIDs of all running instances of the named program" }
      ]
    }
  ],
  strace: [
    {
      line: "execve(\"/bin/ls\", [\"ls\"], 0x7ffe2b8d8e10 /* 25 vars */) = 0",
      segments: [{ text: "execve(\"/bin/ls\", [\"ls\"], 0x7ffe2b8d8e10 /* 25 vars */) = 0", explanation: "System call: execve starts the program execution" }]
    },
    {
      line: "brk(NULL)                               = 0x55a3c8d3b000",
      segments: [{ text: "brk(NULL)                               = 0x55a3c8d3b000", explanation: "System call: brk allocates memory for the process" }]
    },
    {
      line: "openat(AT_FDCWD, \"/etc/ld.so.cache\", O_RDONLY|O_CLOEXEC) = 3",
      segments: [{ text: "openat(AT_FDCWD, \"/etc/ld.so.cache\", O_RDONLY|O_CLOEXEC) = 3", explanation: "System call: openat opens shared libraries needed to run" }]
    },
    {
      line: "read(3, \"\\177ELF\\2\\1\\1\\3\\0\\0\\0\\0\\0\\0\\0\\0\"..., 832) = 832",
      segments: [{ text: "read(3, \"\\177ELF\\2\\1\\1\\3\\0\\0\\0\\0\\0\\0\\0\\0\"..., 832) = 832", explanation: "System call: read performs I/O on the file descriptor" }]
    },
    {
      line: "write(1, \"Desktop\\nDocuments\\nDownloads\\n\"..., 45) = 45",
      segments: [{ text: "write(1, \"Desktop\\nDocuments\\nDownloads\\n\"..., 45) = 45", explanation: "System call: write prints the actual command output to standard out" }]
    },
    {
      line: "+++ exited with 0 +++",
      segments: [{ text: "+++ exited with 0 +++", explanation: "Process exit status (0 means success)" }]
    }
  ],
  time: [
    {
      line: "real    0m0.012s",
      segments: [{ text: "real    0m0.012s", explanation: "real = total wall clock time elapsed from start to finish" }]
    },
    {
      line: "user    0m0.005s",
      segments: [{ text: "user    0m0.005s", explanation: "user = CPU time spent executing the process in user mode" }]
    },
    {
      line: "sys     0m0.007s",
      segments: [{ text: "sys     0m0.007s", explanation: "sys = CPU time spent executing the process in kernel mode" }]
    }
  ],
  nohup: [
    {
      line: "nohup: ignoring input and appending output to 'nohup.out'",
      segments: [
        { text: "nohup: ignoring input and appending output to 'nohup.out'", explanation: "nohup disconnects the process from the terminal, output goes to nohup.out file, process continues after logout." }
      ]
    }
  ],
  renice: [
    {
      line: "1540 (process ID) old priority 0, new priority 10",
      segments: [
        { text: "1540 (process ID) old priority 0, new priority 10", explanation: "shows the process ID, old nice value, and new nice value." }
      ]
    }
  ],
  killall: [
    {
      line: "(no output)",
      segments: [
        { text: "(no output)", explanation: "killall silently sends the signal to all processes matching the name. If no matching processes found, shows 'no process found'." }
      ]
    }
  ]
};